require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatStorageEquipmentsController do

  def mock_boat_storage_equipment(stubs={})
    @mock_boat_storage_equipment ||= mock_model(BoatStorageEquipment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_storage_equipments as @boat_storage_equipments" do
      BoatStorageEquipment.stub(:all) { [mock_boat_storage_equipment] }
      get :index
      assigns(:boat_storage_equipments).should eq([mock_boat_storage_equipment])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_storage_equipment as @boat_storage_equipment" do
      BoatStorageEquipment.stub(:find).with("37") { mock_boat_storage_equipment }
      get :show, :id => "37"
      assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
    end
  end

  describe "GET new" do
    it "assigns a new boat_storage_equipment as @boat_storage_equipment" do
      BoatStorageEquipment.stub(:new) { mock_boat_storage_equipment }
      get :new
      assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_storage_equipment as @boat_storage_equipment" do
      BoatStorageEquipment.stub(:find).with("37") { mock_boat_storage_equipment }
      get :edit, :id => "37"
      assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_storage_equipment as @boat_storage_equipment" do
        BoatStorageEquipment.stub(:new).with({'these' => 'params'}) { mock_boat_storage_equipment(:save => true) }
        post :create, :boat_storage_equipment => {'these' => 'params'}
        assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
      end

      it "redirects to the created boat_storage_equipment" do
        BoatStorageEquipment.stub(:new) { mock_boat_storage_equipment(:save => true) }
        post :create, :boat_storage_equipment => {}
        response.should redirect_to(boat_storage_equipment_url(mock_boat_storage_equipment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_storage_equipment as @boat_storage_equipment" do
        BoatStorageEquipment.stub(:new).with({'these' => 'params'}) { mock_boat_storage_equipment(:save => false) }
        post :create, :boat_storage_equipment => {'these' => 'params'}
        assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
      end

      it "re-renders the 'new' template" do
        BoatStorageEquipment.stub(:new) { mock_boat_storage_equipment(:save => false) }
        post :create, :boat_storage_equipment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_storage_equipment" do
        BoatStorageEquipment.stub(:find).with("37") { mock_boat_storage_equipment }
        mock_boat_storage_equipment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_storage_equipment => {'these' => 'params'}
      end

      it "assigns the requested boat_storage_equipment as @boat_storage_equipment" do
        BoatStorageEquipment.stub(:find) { mock_boat_storage_equipment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
      end

      it "redirects to the boat_storage_equipment" do
        BoatStorageEquipment.stub(:find) { mock_boat_storage_equipment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_storage_equipment_url(mock_boat_storage_equipment))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_storage_equipment as @boat_storage_equipment" do
        BoatStorageEquipment.stub(:find) { mock_boat_storage_equipment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_storage_equipment).should be(mock_boat_storage_equipment)
      end

      it "re-renders the 'edit' template" do
        BoatStorageEquipment.stub(:find) { mock_boat_storage_equipment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_storage_equipment" do
      BoatStorageEquipment.stub(:find).with("37") { mock_boat_storage_equipment }
      mock_boat_storage_equipment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_storage_equipments list" do
      BoatStorageEquipment.stub(:find) { mock_boat_storage_equipment }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_storage_equipments_url)
    end
  end

end
