require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatCoverImageNamesController do

  def mock_boat_cover_image_name(stubs={})
    @mock_boat_cover_image_name ||= mock_model(BoatCoverImageName, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_cover_image_names as @boat_cover_image_names" do
      BoatCoverImageName.stub(:all) { [mock_boat_cover_image_name] }
      get :index
      assigns(:boat_cover_image_names).should eq([mock_boat_cover_image_name])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_cover_image_name as @boat_cover_image_name" do
      BoatCoverImageName.stub(:find).with("37") { mock_boat_cover_image_name }
      get :show, :id => "37"
      assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
    end
  end

  describe "GET new" do
    it "assigns a new boat_cover_image_name as @boat_cover_image_name" do
      BoatCoverImageName.stub(:new) { mock_boat_cover_image_name }
      get :new
      assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_cover_image_name as @boat_cover_image_name" do
      BoatCoverImageName.stub(:find).with("37") { mock_boat_cover_image_name }
      get :edit, :id => "37"
      assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_cover_image_name as @boat_cover_image_name" do
        BoatCoverImageName.stub(:new).with({'these' => 'params'}) { mock_boat_cover_image_name(:save => true) }
        post :create, :boat_cover_image_name => {'these' => 'params'}
        assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
      end

      it "redirects to the created boat_cover_image_name" do
        BoatCoverImageName.stub(:new) { mock_boat_cover_image_name(:save => true) }
        post :create, :boat_cover_image_name => {}
        response.should redirect_to(boat_cover_image_name_url(mock_boat_cover_image_name))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_cover_image_name as @boat_cover_image_name" do
        BoatCoverImageName.stub(:new).with({'these' => 'params'}) { mock_boat_cover_image_name(:save => false) }
        post :create, :boat_cover_image_name => {'these' => 'params'}
        assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
      end

      it "re-renders the 'new' template" do
        BoatCoverImageName.stub(:new) { mock_boat_cover_image_name(:save => false) }
        post :create, :boat_cover_image_name => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_cover_image_name" do
        BoatCoverImageName.stub(:find).with("37") { mock_boat_cover_image_name }
        mock_boat_cover_image_name.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_cover_image_name => {'these' => 'params'}
      end

      it "assigns the requested boat_cover_image_name as @boat_cover_image_name" do
        BoatCoverImageName.stub(:find) { mock_boat_cover_image_name(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
      end

      it "redirects to the boat_cover_image_name" do
        BoatCoverImageName.stub(:find) { mock_boat_cover_image_name(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_cover_image_name_url(mock_boat_cover_image_name))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_cover_image_name as @boat_cover_image_name" do
        BoatCoverImageName.stub(:find) { mock_boat_cover_image_name(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_cover_image_name).should be(mock_boat_cover_image_name)
      end

      it "re-renders the 'edit' template" do
        BoatCoverImageName.stub(:find) { mock_boat_cover_image_name(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_cover_image_name" do
      BoatCoverImageName.stub(:find).with("37") { mock_boat_cover_image_name }
      mock_boat_cover_image_name.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_cover_image_names list" do
      BoatCoverImageName.stub(:find) { mock_boat_cover_image_name }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_cover_image_names_url)
    end
  end

end
