require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatEngineMakesController do

  def mock_boat_engine_make(stubs={})
    @mock_boat_engine_make ||= mock_model(BoatEngineMake, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_engine_makes as @boat_engine_makes" do
      BoatEngineMake.stub(:all) { [mock_boat_engine_make] }
      get :index
      assigns(:boat_engine_makes).should eq([mock_boat_engine_make])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_engine_make as @boat_engine_make" do
      BoatEngineMake.stub(:find).with("37") { mock_boat_engine_make }
      get :show, :id => "37"
      assigns(:boat_engine_make).should be(mock_boat_engine_make)
    end
  end

  describe "GET new" do
    it "assigns a new boat_engine_make as @boat_engine_make" do
      BoatEngineMake.stub(:new) { mock_boat_engine_make }
      get :new
      assigns(:boat_engine_make).should be(mock_boat_engine_make)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_engine_make as @boat_engine_make" do
      BoatEngineMake.stub(:find).with("37") { mock_boat_engine_make }
      get :edit, :id => "37"
      assigns(:boat_engine_make).should be(mock_boat_engine_make)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_engine_make as @boat_engine_make" do
        BoatEngineMake.stub(:new).with({'these' => 'params'}) { mock_boat_engine_make(:save => true) }
        post :create, :boat_engine_make => {'these' => 'params'}
        assigns(:boat_engine_make).should be(mock_boat_engine_make)
      end

      it "redirects to the created boat_engine_make" do
        BoatEngineMake.stub(:new) { mock_boat_engine_make(:save => true) }
        post :create, :boat_engine_make => {}
        response.should redirect_to(boat_engine_make_url(mock_boat_engine_make))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_engine_make as @boat_engine_make" do
        BoatEngineMake.stub(:new).with({'these' => 'params'}) { mock_boat_engine_make(:save => false) }
        post :create, :boat_engine_make => {'these' => 'params'}
        assigns(:boat_engine_make).should be(mock_boat_engine_make)
      end

      it "re-renders the 'new' template" do
        BoatEngineMake.stub(:new) { mock_boat_engine_make(:save => false) }
        post :create, :boat_engine_make => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_engine_make" do
        BoatEngineMake.stub(:find).with("37") { mock_boat_engine_make }
        mock_boat_engine_make.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_engine_make => {'these' => 'params'}
      end

      it "assigns the requested boat_engine_make as @boat_engine_make" do
        BoatEngineMake.stub(:find) { mock_boat_engine_make(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_engine_make).should be(mock_boat_engine_make)
      end

      it "redirects to the boat_engine_make" do
        BoatEngineMake.stub(:find) { mock_boat_engine_make(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_engine_make_url(mock_boat_engine_make))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_engine_make as @boat_engine_make" do
        BoatEngineMake.stub(:find) { mock_boat_engine_make(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_engine_make).should be(mock_boat_engine_make)
      end

      it "re-renders the 'edit' template" do
        BoatEngineMake.stub(:find) { mock_boat_engine_make(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_engine_make" do
      BoatEngineMake.stub(:find).with("37") { mock_boat_engine_make }
      mock_boat_engine_make.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_engine_makes list" do
      BoatEngineMake.stub(:find) { mock_boat_engine_make }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_engine_makes_url)
    end
  end

end
