require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatTypesController do

  def mock_boat_type(stubs={})
    @mock_boat_type ||= mock_model(BoatType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_types as @boat_types" do
      BoatType.stub(:all) { [mock_boat_type] }
      get :index
      assigns(:boat_types).should eq([mock_boat_type])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_type as @boat_type" do
      BoatType.stub(:find).with("37") { mock_boat_type }
      get :show, :id => "37"
      assigns(:boat_type).should be(mock_boat_type)
    end
  end

  describe "GET new" do
    it "assigns a new boat_type as @boat_type" do
      BoatType.stub(:new) { mock_boat_type }
      get :new
      assigns(:boat_type).should be(mock_boat_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_type as @boat_type" do
      BoatType.stub(:find).with("37") { mock_boat_type }
      get :edit, :id => "37"
      assigns(:boat_type).should be(mock_boat_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_type as @boat_type" do
        BoatType.stub(:new).with({'these' => 'params'}) { mock_boat_type(:save => true) }
        post :create, :boat_type => {'these' => 'params'}
        assigns(:boat_type).should be(mock_boat_type)
      end

      it "redirects to the created boat_type" do
        BoatType.stub(:new) { mock_boat_type(:save => true) }
        post :create, :boat_type => {}
        response.should redirect_to(boat_type_url(mock_boat_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_type as @boat_type" do
        BoatType.stub(:new).with({'these' => 'params'}) { mock_boat_type(:save => false) }
        post :create, :boat_type => {'these' => 'params'}
        assigns(:boat_type).should be(mock_boat_type)
      end

      it "re-renders the 'new' template" do
        BoatType.stub(:new) { mock_boat_type(:save => false) }
        post :create, :boat_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_type" do
        BoatType.stub(:find).with("37") { mock_boat_type }
        mock_boat_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_type => {'these' => 'params'}
      end

      it "assigns the requested boat_type as @boat_type" do
        BoatType.stub(:find) { mock_boat_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_type).should be(mock_boat_type)
      end

      it "redirects to the boat_type" do
        BoatType.stub(:find) { mock_boat_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_type_url(mock_boat_type))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_type as @boat_type" do
        BoatType.stub(:find) { mock_boat_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_type).should be(mock_boat_type)
      end

      it "re-renders the 'edit' template" do
        BoatType.stub(:find) { mock_boat_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_type" do
      BoatType.stub(:find).with("37") { mock_boat_type }
      mock_boat_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_types list" do
      BoatType.stub(:find) { mock_boat_type }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_types_url)
    end
  end

end
