require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatAskingPricesController do

  def mock_boat_asking_price(stubs={})
    @mock_boat_asking_price ||= mock_model(BoatAskingPrice, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_asking_prices as @boat_asking_prices" do
      BoatAskingPrice.stub(:all) { [mock_boat_asking_price] }
      get :index
      assigns(:boat_asking_prices).should eq([mock_boat_asking_price])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_asking_price as @boat_asking_price" do
      BoatAskingPrice.stub(:find).with("37") { mock_boat_asking_price }
      get :show, :id => "37"
      assigns(:boat_asking_price).should be(mock_boat_asking_price)
    end
  end

  describe "GET new" do
    it "assigns a new boat_asking_price as @boat_asking_price" do
      BoatAskingPrice.stub(:new) { mock_boat_asking_price }
      get :new
      assigns(:boat_asking_price).should be(mock_boat_asking_price)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_asking_price as @boat_asking_price" do
      BoatAskingPrice.stub(:find).with("37") { mock_boat_asking_price }
      get :edit, :id => "37"
      assigns(:boat_asking_price).should be(mock_boat_asking_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_asking_price as @boat_asking_price" do
        BoatAskingPrice.stub(:new).with({'these' => 'params'}) { mock_boat_asking_price(:save => true) }
        post :create, :boat_asking_price => {'these' => 'params'}
        assigns(:boat_asking_price).should be(mock_boat_asking_price)
      end

      it "redirects to the created boat_asking_price" do
        BoatAskingPrice.stub(:new) { mock_boat_asking_price(:save => true) }
        post :create, :boat_asking_price => {}
        response.should redirect_to(boat_asking_price_url(mock_boat_asking_price))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_asking_price as @boat_asking_price" do
        BoatAskingPrice.stub(:new).with({'these' => 'params'}) { mock_boat_asking_price(:save => false) }
        post :create, :boat_asking_price => {'these' => 'params'}
        assigns(:boat_asking_price).should be(mock_boat_asking_price)
      end

      it "re-renders the 'new' template" do
        BoatAskingPrice.stub(:new) { mock_boat_asking_price(:save => false) }
        post :create, :boat_asking_price => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_asking_price" do
        BoatAskingPrice.stub(:find).with("37") { mock_boat_asking_price }
        mock_boat_asking_price.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_asking_price => {'these' => 'params'}
      end

      it "assigns the requested boat_asking_price as @boat_asking_price" do
        BoatAskingPrice.stub(:find) { mock_boat_asking_price(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_asking_price).should be(mock_boat_asking_price)
      end

      it "redirects to the boat_asking_price" do
        BoatAskingPrice.stub(:find) { mock_boat_asking_price(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_asking_price_url(mock_boat_asking_price))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_asking_price as @boat_asking_price" do
        BoatAskingPrice.stub(:find) { mock_boat_asking_price(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_asking_price).should be(mock_boat_asking_price)
      end

      it "re-renders the 'edit' template" do
        BoatAskingPrice.stub(:find) { mock_boat_asking_price(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_asking_price" do
      BoatAskingPrice.stub(:find).with("37") { mock_boat_asking_price }
      mock_boat_asking_price.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_asking_prices list" do
      BoatAskingPrice.stub(:find) { mock_boat_asking_price }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_asking_prices_url)
    end
  end

end
