require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatsDomicileTypeSectionsController do

  def mock_boats_domicile_type_section(stubs={})
    @mock_boats_domicile_type_section ||= mock_model(BoatsDomicileTypeSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boats_domicile_type_sections as @boats_domicile_type_sections" do
      BoatsDomicileTypeSection.stub(:all) { [mock_boats_domicile_type_section] }
      get :index
      assigns(:boats_domicile_type_sections).should eq([mock_boats_domicile_type_section])
    end
  end

  describe "GET show" do
    it "assigns the requested boats_domicile_type_section as @boats_domicile_type_section" do
      BoatsDomicileTypeSection.stub(:find).with("37") { mock_boats_domicile_type_section }
      get :show, :id => "37"
      assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
    end
  end

  describe "GET new" do
    it "assigns a new boats_domicile_type_section as @boats_domicile_type_section" do
      BoatsDomicileTypeSection.stub(:new) { mock_boats_domicile_type_section }
      get :new
      assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested boats_domicile_type_section as @boats_domicile_type_section" do
      BoatsDomicileTypeSection.stub(:find).with("37") { mock_boats_domicile_type_section }
      get :edit, :id => "37"
      assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boats_domicile_type_section as @boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:new).with({'these' => 'params'}) { mock_boats_domicile_type_section(:save => true) }
        post :create, :boats_domicile_type_section => {'these' => 'params'}
        assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
      end

      it "redirects to the created boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:new) { mock_boats_domicile_type_section(:save => true) }
        post :create, :boats_domicile_type_section => {}
        response.should redirect_to(boats_domicile_type_section_url(mock_boats_domicile_type_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boats_domicile_type_section as @boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:new).with({'these' => 'params'}) { mock_boats_domicile_type_section(:save => false) }
        post :create, :boats_domicile_type_section => {'these' => 'params'}
        assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
      end

      it "re-renders the 'new' template" do
        BoatsDomicileTypeSection.stub(:new) { mock_boats_domicile_type_section(:save => false) }
        post :create, :boats_domicile_type_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:find).with("37") { mock_boats_domicile_type_section }
        mock_boats_domicile_type_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boats_domicile_type_section => {'these' => 'params'}
      end

      it "assigns the requested boats_domicile_type_section as @boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:find) { mock_boats_domicile_type_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
      end

      it "redirects to the boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:find) { mock_boats_domicile_type_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boats_domicile_type_section_url(mock_boats_domicile_type_section))
      end
    end

    describe "with invalid params" do
      it "assigns the boats_domicile_type_section as @boats_domicile_type_section" do
        BoatsDomicileTypeSection.stub(:find) { mock_boats_domicile_type_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boats_domicile_type_section).should be(mock_boats_domicile_type_section)
      end

      it "re-renders the 'edit' template" do
        BoatsDomicileTypeSection.stub(:find) { mock_boats_domicile_type_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boats_domicile_type_section" do
      BoatsDomicileTypeSection.stub(:find).with("37") { mock_boats_domicile_type_section }
      mock_boats_domicile_type_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boats_domicile_type_sections list" do
      BoatsDomicileTypeSection.stub(:find) { mock_boats_domicile_type_section }
      delete :destroy, :id => "1"
      response.should redirect_to(boats_domicile_type_sections_url)
    end
  end

end
