require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatCoverImageUidsController do

  def mock_boat_cover_image_uid(stubs={})
    @mock_boat_cover_image_uid ||= mock_model(BoatCoverImageUid, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_cover_image_uids as @boat_cover_image_uids" do
      BoatCoverImageUid.stub(:all) { [mock_boat_cover_image_uid] }
      get :index
      assigns(:boat_cover_image_uids).should eq([mock_boat_cover_image_uid])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_cover_image_uid as @boat_cover_image_uid" do
      BoatCoverImageUid.stub(:find).with("37") { mock_boat_cover_image_uid }
      get :show, :id => "37"
      assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
    end
  end

  describe "GET new" do
    it "assigns a new boat_cover_image_uid as @boat_cover_image_uid" do
      BoatCoverImageUid.stub(:new) { mock_boat_cover_image_uid }
      get :new
      assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_cover_image_uid as @boat_cover_image_uid" do
      BoatCoverImageUid.stub(:find).with("37") { mock_boat_cover_image_uid }
      get :edit, :id => "37"
      assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_cover_image_uid as @boat_cover_image_uid" do
        BoatCoverImageUid.stub(:new).with({'these' => 'params'}) { mock_boat_cover_image_uid(:save => true) }
        post :create, :boat_cover_image_uid => {'these' => 'params'}
        assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
      end

      it "redirects to the created boat_cover_image_uid" do
        BoatCoverImageUid.stub(:new) { mock_boat_cover_image_uid(:save => true) }
        post :create, :boat_cover_image_uid => {}
        response.should redirect_to(boat_cover_image_uid_url(mock_boat_cover_image_uid))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_cover_image_uid as @boat_cover_image_uid" do
        BoatCoverImageUid.stub(:new).with({'these' => 'params'}) { mock_boat_cover_image_uid(:save => false) }
        post :create, :boat_cover_image_uid => {'these' => 'params'}
        assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
      end

      it "re-renders the 'new' template" do
        BoatCoverImageUid.stub(:new) { mock_boat_cover_image_uid(:save => false) }
        post :create, :boat_cover_image_uid => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_cover_image_uid" do
        BoatCoverImageUid.stub(:find).with("37") { mock_boat_cover_image_uid }
        mock_boat_cover_image_uid.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_cover_image_uid => {'these' => 'params'}
      end

      it "assigns the requested boat_cover_image_uid as @boat_cover_image_uid" do
        BoatCoverImageUid.stub(:find) { mock_boat_cover_image_uid(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
      end

      it "redirects to the boat_cover_image_uid" do
        BoatCoverImageUid.stub(:find) { mock_boat_cover_image_uid(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_cover_image_uid_url(mock_boat_cover_image_uid))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_cover_image_uid as @boat_cover_image_uid" do
        BoatCoverImageUid.stub(:find) { mock_boat_cover_image_uid(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_cover_image_uid).should be(mock_boat_cover_image_uid)
      end

      it "re-renders the 'edit' template" do
        BoatCoverImageUid.stub(:find) { mock_boat_cover_image_uid(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_cover_image_uid" do
      BoatCoverImageUid.stub(:find).with("37") { mock_boat_cover_image_uid }
      mock_boat_cover_image_uid.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_cover_image_uids list" do
      BoatCoverImageUid.stub(:find) { mock_boat_cover_image_uid }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_cover_image_uids_url)
    end
  end

end
