require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatWeightsController do

  def mock_boat_weight(stubs={})
    @mock_boat_weight ||= mock_model(BoatWeight, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_weights as @boat_weights" do
      BoatWeight.stub(:all) { [mock_boat_weight] }
      get :index
      assigns(:boat_weights).should eq([mock_boat_weight])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_weight as @boat_weight" do
      BoatWeight.stub(:find).with("37") { mock_boat_weight }
      get :show, :id => "37"
      assigns(:boat_weight).should be(mock_boat_weight)
    end
  end

  describe "GET new" do
    it "assigns a new boat_weight as @boat_weight" do
      BoatWeight.stub(:new) { mock_boat_weight }
      get :new
      assigns(:boat_weight).should be(mock_boat_weight)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_weight as @boat_weight" do
      BoatWeight.stub(:find).with("37") { mock_boat_weight }
      get :edit, :id => "37"
      assigns(:boat_weight).should be(mock_boat_weight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_weight as @boat_weight" do
        BoatWeight.stub(:new).with({'these' => 'params'}) { mock_boat_weight(:save => true) }
        post :create, :boat_weight => {'these' => 'params'}
        assigns(:boat_weight).should be(mock_boat_weight)
      end

      it "redirects to the created boat_weight" do
        BoatWeight.stub(:new) { mock_boat_weight(:save => true) }
        post :create, :boat_weight => {}
        response.should redirect_to(boat_weight_url(mock_boat_weight))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_weight as @boat_weight" do
        BoatWeight.stub(:new).with({'these' => 'params'}) { mock_boat_weight(:save => false) }
        post :create, :boat_weight => {'these' => 'params'}
        assigns(:boat_weight).should be(mock_boat_weight)
      end

      it "re-renders the 'new' template" do
        BoatWeight.stub(:new) { mock_boat_weight(:save => false) }
        post :create, :boat_weight => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_weight" do
        BoatWeight.stub(:find).with("37") { mock_boat_weight }
        mock_boat_weight.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_weight => {'these' => 'params'}
      end

      it "assigns the requested boat_weight as @boat_weight" do
        BoatWeight.stub(:find) { mock_boat_weight(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_weight).should be(mock_boat_weight)
      end

      it "redirects to the boat_weight" do
        BoatWeight.stub(:find) { mock_boat_weight(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_weight_url(mock_boat_weight))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_weight as @boat_weight" do
        BoatWeight.stub(:find) { mock_boat_weight(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_weight).should be(mock_boat_weight)
      end

      it "re-renders the 'edit' template" do
        BoatWeight.stub(:find) { mock_boat_weight(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_weight" do
      BoatWeight.stub(:find).with("37") { mock_boat_weight }
      mock_boat_weight.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_weights list" do
      BoatWeight.stub(:find) { mock_boat_weight }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_weights_url)
    end
  end

end
