require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatsController do

  def mock_boat(stubs={})
    @mock_boat ||= mock_model(Boat, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boats as @boats" do
      Boat.stub(:all) { [mock_boat] }
      get :index
      assigns(:boats).should eq([mock_boat])
    end
  end

  describe "GET show" do
    it "assigns the requested boat as @boat" do
      Boat.stub(:find).with("37") { mock_boat }
      get :show, :id => "37"
      assigns(:boat).should be(mock_boat)
    end
  end

  describe "GET new" do
    it "assigns a new boat as @boat" do
      Boat.stub(:new) { mock_boat }
      get :new
      assigns(:boat).should be(mock_boat)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat as @boat" do
      Boat.stub(:find).with("37") { mock_boat }
      get :edit, :id => "37"
      assigns(:boat).should be(mock_boat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat as @boat" do
        Boat.stub(:new).with({'these' => 'params'}) { mock_boat(:save => true) }
        post :create, :boat => {'these' => 'params'}
        assigns(:boat).should be(mock_boat)
      end

      it "redirects to the created boat" do
        Boat.stub(:new) { mock_boat(:save => true) }
        post :create, :boat => {}
        response.should redirect_to(boat_url(mock_boat))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat as @boat" do
        Boat.stub(:new).with({'these' => 'params'}) { mock_boat(:save => false) }
        post :create, :boat => {'these' => 'params'}
        assigns(:boat).should be(mock_boat)
      end

      it "re-renders the 'new' template" do
        Boat.stub(:new) { mock_boat(:save => false) }
        post :create, :boat => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat" do
        Boat.stub(:find).with("37") { mock_boat }
        mock_boat.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat => {'these' => 'params'}
      end

      it "assigns the requested boat as @boat" do
        Boat.stub(:find) { mock_boat(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat).should be(mock_boat)
      end

      it "redirects to the boat" do
        Boat.stub(:find) { mock_boat(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_url(mock_boat))
      end
    end

    describe "with invalid params" do
      it "assigns the boat as @boat" do
        Boat.stub(:find) { mock_boat(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat).should be(mock_boat)
      end

      it "re-renders the 'edit' template" do
        Boat.stub(:find) { mock_boat(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat" do
      Boat.stub(:find).with("37") { mock_boat }
      mock_boat.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boats list" do
      Boat.stub(:find) { mock_boat }
      delete :destroy, :id => "1"
      response.should redirect_to(boats_url)
    end
  end

end
