require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatNotesController do

  def mock_boat_note(stubs={})
    @mock_boat_note ||= mock_model(BoatNote, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_notes as @boat_notes" do
      BoatNote.stub(:all) { [mock_boat_note] }
      get :index
      assigns(:boat_notes).should eq([mock_boat_note])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_note as @boat_note" do
      BoatNote.stub(:find).with("37") { mock_boat_note }
      get :show, :id => "37"
      assigns(:boat_note).should be(mock_boat_note)
    end
  end

  describe "GET new" do
    it "assigns a new boat_note as @boat_note" do
      BoatNote.stub(:new) { mock_boat_note }
      get :new
      assigns(:boat_note).should be(mock_boat_note)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_note as @boat_note" do
      BoatNote.stub(:find).with("37") { mock_boat_note }
      get :edit, :id => "37"
      assigns(:boat_note).should be(mock_boat_note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_note as @boat_note" do
        BoatNote.stub(:new).with({'these' => 'params'}) { mock_boat_note(:save => true) }
        post :create, :boat_note => {'these' => 'params'}
        assigns(:boat_note).should be(mock_boat_note)
      end

      it "redirects to the created boat_note" do
        BoatNote.stub(:new) { mock_boat_note(:save => true) }
        post :create, :boat_note => {}
        response.should redirect_to(boat_note_url(mock_boat_note))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_note as @boat_note" do
        BoatNote.stub(:new).with({'these' => 'params'}) { mock_boat_note(:save => false) }
        post :create, :boat_note => {'these' => 'params'}
        assigns(:boat_note).should be(mock_boat_note)
      end

      it "re-renders the 'new' template" do
        BoatNote.stub(:new) { mock_boat_note(:save => false) }
        post :create, :boat_note => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_note" do
        BoatNote.stub(:find).with("37") { mock_boat_note }
        mock_boat_note.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_note => {'these' => 'params'}
      end

      it "assigns the requested boat_note as @boat_note" do
        BoatNote.stub(:find) { mock_boat_note(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_note).should be(mock_boat_note)
      end

      it "redirects to the boat_note" do
        BoatNote.stub(:find) { mock_boat_note(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_note_url(mock_boat_note))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_note as @boat_note" do
        BoatNote.stub(:find) { mock_boat_note(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_note).should be(mock_boat_note)
      end

      it "re-renders the 'edit' template" do
        BoatNote.stub(:find) { mock_boat_note(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_note" do
      BoatNote.stub(:find).with("37") { mock_boat_note }
      mock_boat_note.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_notes list" do
      BoatNote.stub(:find) { mock_boat_note }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_notes_url)
    end
  end

end
