require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatSubtypeSectionsController do

  def mock_boat_subtype_section(stubs={})
    @mock_boat_subtype_section ||= mock_model(BoatSubtypeSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_subtype_sections as @boat_subtype_sections" do
      BoatSubtypeSection.stub(:all) { [mock_boat_subtype_section] }
      get :index
      assigns(:boat_subtype_sections).should eq([mock_boat_subtype_section])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_subtype_section as @boat_subtype_section" do
      BoatSubtypeSection.stub(:find).with("37") { mock_boat_subtype_section }
      get :show, :id => "37"
      assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
    end
  end

  describe "GET new" do
    it "assigns a new boat_subtype_section as @boat_subtype_section" do
      BoatSubtypeSection.stub(:new) { mock_boat_subtype_section }
      get :new
      assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_subtype_section as @boat_subtype_section" do
      BoatSubtypeSection.stub(:find).with("37") { mock_boat_subtype_section }
      get :edit, :id => "37"
      assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_subtype_section as @boat_subtype_section" do
        BoatSubtypeSection.stub(:new).with({'these' => 'params'}) { mock_boat_subtype_section(:save => true) }
        post :create, :boat_subtype_section => {'these' => 'params'}
        assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
      end

      it "redirects to the created boat_subtype_section" do
        BoatSubtypeSection.stub(:new) { mock_boat_subtype_section(:save => true) }
        post :create, :boat_subtype_section => {}
        response.should redirect_to(boat_subtype_section_url(mock_boat_subtype_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_subtype_section as @boat_subtype_section" do
        BoatSubtypeSection.stub(:new).with({'these' => 'params'}) { mock_boat_subtype_section(:save => false) }
        post :create, :boat_subtype_section => {'these' => 'params'}
        assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
      end

      it "re-renders the 'new' template" do
        BoatSubtypeSection.stub(:new) { mock_boat_subtype_section(:save => false) }
        post :create, :boat_subtype_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_subtype_section" do
        BoatSubtypeSection.stub(:find).with("37") { mock_boat_subtype_section }
        mock_boat_subtype_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_subtype_section => {'these' => 'params'}
      end

      it "assigns the requested boat_subtype_section as @boat_subtype_section" do
        BoatSubtypeSection.stub(:find) { mock_boat_subtype_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
      end

      it "redirects to the boat_subtype_section" do
        BoatSubtypeSection.stub(:find) { mock_boat_subtype_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_subtype_section_url(mock_boat_subtype_section))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_subtype_section as @boat_subtype_section" do
        BoatSubtypeSection.stub(:find) { mock_boat_subtype_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_subtype_section).should be(mock_boat_subtype_section)
      end

      it "re-renders the 'edit' template" do
        BoatSubtypeSection.stub(:find) { mock_boat_subtype_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_subtype_section" do
      BoatSubtypeSection.stub(:find).with("37") { mock_boat_subtype_section }
      mock_boat_subtype_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_subtype_sections list" do
      BoatSubtypeSection.stub(:find) { mock_boat_subtype_section }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_subtype_sections_url)
    end
  end

end
