require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoatWidthsController do

  def mock_boat_width(stubs={})
    @mock_boat_width ||= mock_model(BoatWidth, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boat_widths as @boat_widths" do
      BoatWidth.stub(:all) { [mock_boat_width] }
      get :index
      assigns(:boat_widths).should eq([mock_boat_width])
    end
  end

  describe "GET show" do
    it "assigns the requested boat_width as @boat_width" do
      BoatWidth.stub(:find).with("37") { mock_boat_width }
      get :show, :id => "37"
      assigns(:boat_width).should be(mock_boat_width)
    end
  end

  describe "GET new" do
    it "assigns a new boat_width as @boat_width" do
      BoatWidth.stub(:new) { mock_boat_width }
      get :new
      assigns(:boat_width).should be(mock_boat_width)
    end
  end

  describe "GET edit" do
    it "assigns the requested boat_width as @boat_width" do
      BoatWidth.stub(:find).with("37") { mock_boat_width }
      get :edit, :id => "37"
      assigns(:boat_width).should be(mock_boat_width)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created boat_width as @boat_width" do
        BoatWidth.stub(:new).with({'these' => 'params'}) { mock_boat_width(:save => true) }
        post :create, :boat_width => {'these' => 'params'}
        assigns(:boat_width).should be(mock_boat_width)
      end

      it "redirects to the created boat_width" do
        BoatWidth.stub(:new) { mock_boat_width(:save => true) }
        post :create, :boat_width => {}
        response.should redirect_to(boat_width_url(mock_boat_width))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boat_width as @boat_width" do
        BoatWidth.stub(:new).with({'these' => 'params'}) { mock_boat_width(:save => false) }
        post :create, :boat_width => {'these' => 'params'}
        assigns(:boat_width).should be(mock_boat_width)
      end

      it "re-renders the 'new' template" do
        BoatWidth.stub(:new) { mock_boat_width(:save => false) }
        post :create, :boat_width => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boat_width" do
        BoatWidth.stub(:find).with("37") { mock_boat_width }
        mock_boat_width.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :boat_width => {'these' => 'params'}
      end

      it "assigns the requested boat_width as @boat_width" do
        BoatWidth.stub(:find) { mock_boat_width(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:boat_width).should be(mock_boat_width)
      end

      it "redirects to the boat_width" do
        BoatWidth.stub(:find) { mock_boat_width(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(boat_width_url(mock_boat_width))
      end
    end

    describe "with invalid params" do
      it "assigns the boat_width as @boat_width" do
        BoatWidth.stub(:find) { mock_boat_width(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:boat_width).should be(mock_boat_width)
      end

      it "re-renders the 'edit' template" do
        BoatWidth.stub(:find) { mock_boat_width(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boat_width" do
      BoatWidth.stub(:find).with("37") { mock_boat_width }
      mock_boat_width.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boat_widths list" do
      BoatWidth.stub(:find) { mock_boat_width }
      delete :destroy, :id => "1"
      response.should redirect_to(boat_widths_url)
    end
  end

end
