require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CarAccelerationsController do

  def mock_car_acceleration(stubs={})
    @mock_car_acceleration ||= mock_model(CarAcceleration, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all car_accelerations as @car_accelerations" do
      CarAcceleration.stub(:all) { [mock_car_acceleration] }
      get :index
      assigns(:car_accelerations).should eq([mock_car_acceleration])
    end
  end

  describe "GET show" do
    it "assigns the requested car_acceleration as @car_acceleration" do
      CarAcceleration.stub(:find).with("37") { mock_car_acceleration }
      get :show, :id => "37"
      assigns(:car_acceleration).should be(mock_car_acceleration)
    end
  end

  describe "GET new" do
    it "assigns a new car_acceleration as @car_acceleration" do
      CarAcceleration.stub(:new) { mock_car_acceleration }
      get :new
      assigns(:car_acceleration).should be(mock_car_acceleration)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_acceleration as @car_acceleration" do
      CarAcceleration.stub(:find).with("37") { mock_car_acceleration }
      get :edit, :id => "37"
      assigns(:car_acceleration).should be(mock_car_acceleration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created car_acceleration as @car_acceleration" do
        CarAcceleration.stub(:new).with({'these' => 'params'}) { mock_car_acceleration(:save => true) }
        post :create, :car_acceleration => {'these' => 'params'}
        assigns(:car_acceleration).should be(mock_car_acceleration)
      end

      it "redirects to the created car_acceleration" do
        CarAcceleration.stub(:new) { mock_car_acceleration(:save => true) }
        post :create, :car_acceleration => {}
        response.should redirect_to(car_acceleration_url(mock_car_acceleration))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_acceleration as @car_acceleration" do
        CarAcceleration.stub(:new).with({'these' => 'params'}) { mock_car_acceleration(:save => false) }
        post :create, :car_acceleration => {'these' => 'params'}
        assigns(:car_acceleration).should be(mock_car_acceleration)
      end

      it "re-renders the 'new' template" do
        CarAcceleration.stub(:new) { mock_car_acceleration(:save => false) }
        post :create, :car_acceleration => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_acceleration" do
        CarAcceleration.stub(:find).with("37") { mock_car_acceleration }
        mock_car_acceleration.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :car_acceleration => {'these' => 'params'}
      end

      it "assigns the requested car_acceleration as @car_acceleration" do
        CarAcceleration.stub(:find) { mock_car_acceleration(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:car_acceleration).should be(mock_car_acceleration)
      end

      it "redirects to the car_acceleration" do
        CarAcceleration.stub(:find) { mock_car_acceleration(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(car_acceleration_url(mock_car_acceleration))
      end
    end

    describe "with invalid params" do
      it "assigns the car_acceleration as @car_acceleration" do
        CarAcceleration.stub(:find) { mock_car_acceleration(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:car_acceleration).should be(mock_car_acceleration)
      end

      it "re-renders the 'edit' template" do
        CarAcceleration.stub(:find) { mock_car_acceleration(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_acceleration" do
      CarAcceleration.stub(:find).with("37") { mock_car_acceleration }
      mock_car_acceleration.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the car_accelerations list" do
      CarAcceleration.stub(:find) { mock_car_acceleration }
      delete :destroy, :id => "1"
      response.should redirect_to(car_accelerations_url)
    end
  end

end
