require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CarPostsController do

  def mock_car_post(stubs={})
    @mock_car_post ||= mock_model(CarPost, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all car_posts as @car_posts" do
      CarPost.stub(:all) { [mock_car_post] }
      get :index
      assigns(:car_posts).should eq([mock_car_post])
    end
  end

  describe "GET show" do
    it "assigns the requested car_post as @car_post" do
      CarPost.stub(:find).with("37") { mock_car_post }
      get :show, :id => "37"
      assigns(:car_post).should be(mock_car_post)
    end
  end

  describe "GET new" do
    it "assigns a new car_post as @car_post" do
      CarPost.stub(:new) { mock_car_post }
      get :new
      assigns(:car_post).should be(mock_car_post)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_post as @car_post" do
      CarPost.stub(:find).with("37") { mock_car_post }
      get :edit, :id => "37"
      assigns(:car_post).should be(mock_car_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created car_post as @car_post" do
        CarPost.stub(:new).with({'these' => 'params'}) { mock_car_post(:save => true) }
        post :create, :car_post => {'these' => 'params'}
        assigns(:car_post).should be(mock_car_post)
      end

      it "redirects to the created car_post" do
        CarPost.stub(:new) { mock_car_post(:save => true) }
        post :create, :car_post => {}
        response.should redirect_to(car_post_url(mock_car_post))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_post as @car_post" do
        CarPost.stub(:new).with({'these' => 'params'}) { mock_car_post(:save => false) }
        post :create, :car_post => {'these' => 'params'}
        assigns(:car_post).should be(mock_car_post)
      end

      it "re-renders the 'new' template" do
        CarPost.stub(:new) { mock_car_post(:save => false) }
        post :create, :car_post => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_post" do
        CarPost.stub(:find).with("37") { mock_car_post }
        mock_car_post.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :car_post => {'these' => 'params'}
      end

      it "assigns the requested car_post as @car_post" do
        CarPost.stub(:find) { mock_car_post(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:car_post).should be(mock_car_post)
      end

      it "redirects to the car_post" do
        CarPost.stub(:find) { mock_car_post(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(car_post_url(mock_car_post))
      end
    end

    describe "with invalid params" do
      it "assigns the car_post as @car_post" do
        CarPost.stub(:find) { mock_car_post(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:car_post).should be(mock_car_post)
      end

      it "re-renders the 'edit' template" do
        CarPost.stub(:find) { mock_car_post(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_post" do
      CarPost.stub(:find).with("37") { mock_car_post }
      mock_car_post.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the car_posts list" do
      CarPost.stub(:find) { mock_car_post }
      delete :destroy, :id => "1"
      response.should redirect_to(car_posts_url)
    end
  end

end
