require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CarTopSpeedsController do

  def mock_car_top_speed(stubs={})
    @mock_car_top_speed ||= mock_model(CarTopSpeed, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all car_top_speeds as @car_top_speeds" do
      CarTopSpeed.stub(:all) { [mock_car_top_speed] }
      get :index
      assigns(:car_top_speeds).should eq([mock_car_top_speed])
    end
  end

  describe "GET show" do
    it "assigns the requested car_top_speed as @car_top_speed" do
      CarTopSpeed.stub(:find).with("37") { mock_car_top_speed }
      get :show, :id => "37"
      assigns(:car_top_speed).should be(mock_car_top_speed)
    end
  end

  describe "GET new" do
    it "assigns a new car_top_speed as @car_top_speed" do
      CarTopSpeed.stub(:new) { mock_car_top_speed }
      get :new
      assigns(:car_top_speed).should be(mock_car_top_speed)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_top_speed as @car_top_speed" do
      CarTopSpeed.stub(:find).with("37") { mock_car_top_speed }
      get :edit, :id => "37"
      assigns(:car_top_speed).should be(mock_car_top_speed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created car_top_speed as @car_top_speed" do
        CarTopSpeed.stub(:new).with({'these' => 'params'}) { mock_car_top_speed(:save => true) }
        post :create, :car_top_speed => {'these' => 'params'}
        assigns(:car_top_speed).should be(mock_car_top_speed)
      end

      it "redirects to the created car_top_speed" do
        CarTopSpeed.stub(:new) { mock_car_top_speed(:save => true) }
        post :create, :car_top_speed => {}
        response.should redirect_to(car_top_speed_url(mock_car_top_speed))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_top_speed as @car_top_speed" do
        CarTopSpeed.stub(:new).with({'these' => 'params'}) { mock_car_top_speed(:save => false) }
        post :create, :car_top_speed => {'these' => 'params'}
        assigns(:car_top_speed).should be(mock_car_top_speed)
      end

      it "re-renders the 'new' template" do
        CarTopSpeed.stub(:new) { mock_car_top_speed(:save => false) }
        post :create, :car_top_speed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_top_speed" do
        CarTopSpeed.stub(:find).with("37") { mock_car_top_speed }
        mock_car_top_speed.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :car_top_speed => {'these' => 'params'}
      end

      it "assigns the requested car_top_speed as @car_top_speed" do
        CarTopSpeed.stub(:find) { mock_car_top_speed(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:car_top_speed).should be(mock_car_top_speed)
      end

      it "redirects to the car_top_speed" do
        CarTopSpeed.stub(:find) { mock_car_top_speed(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(car_top_speed_url(mock_car_top_speed))
      end
    end

    describe "with invalid params" do
      it "assigns the car_top_speed as @car_top_speed" do
        CarTopSpeed.stub(:find) { mock_car_top_speed(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:car_top_speed).should be(mock_car_top_speed)
      end

      it "re-renders the 'edit' template" do
        CarTopSpeed.stub(:find) { mock_car_top_speed(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_top_speed" do
      CarTopSpeed.stub(:find).with("37") { mock_car_top_speed }
      mock_car_top_speed.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the car_top_speeds list" do
      CarTopSpeed.stub(:find) { mock_car_top_speed }
      delete :destroy, :id => "1"
      response.should redirect_to(car_top_speeds_url)
    end
  end

end
