require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CarYearModelsController do

  def mock_car_year_model(stubs={})
    @mock_car_year_model ||= mock_model(CarYearModel, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all car_year_models as @car_year_models" do
      CarYearModel.stub(:all) { [mock_car_year_model] }
      get :index
      assigns(:car_year_models).should eq([mock_car_year_model])
    end
  end

  describe "GET show" do
    it "assigns the requested car_year_model as @car_year_model" do
      CarYearModel.stub(:find).with("37") { mock_car_year_model }
      get :show, :id => "37"
      assigns(:car_year_model).should be(mock_car_year_model)
    end
  end

  describe "GET new" do
    it "assigns a new car_year_model as @car_year_model" do
      CarYearModel.stub(:new) { mock_car_year_model }
      get :new
      assigns(:car_year_model).should be(mock_car_year_model)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_year_model as @car_year_model" do
      CarYearModel.stub(:find).with("37") { mock_car_year_model }
      get :edit, :id => "37"
      assigns(:car_year_model).should be(mock_car_year_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created car_year_model as @car_year_model" do
        CarYearModel.stub(:new).with({'these' => 'params'}) { mock_car_year_model(:save => true) }
        post :create, :car_year_model => {'these' => 'params'}
        assigns(:car_year_model).should be(mock_car_year_model)
      end

      it "redirects to the created car_year_model" do
        CarYearModel.stub(:new) { mock_car_year_model(:save => true) }
        post :create, :car_year_model => {}
        response.should redirect_to(car_year_model_url(mock_car_year_model))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_year_model as @car_year_model" do
        CarYearModel.stub(:new).with({'these' => 'params'}) { mock_car_year_model(:save => false) }
        post :create, :car_year_model => {'these' => 'params'}
        assigns(:car_year_model).should be(mock_car_year_model)
      end

      it "re-renders the 'new' template" do
        CarYearModel.stub(:new) { mock_car_year_model(:save => false) }
        post :create, :car_year_model => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_year_model" do
        CarYearModel.stub(:find).with("37") { mock_car_year_model }
        mock_car_year_model.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :car_year_model => {'these' => 'params'}
      end

      it "assigns the requested car_year_model as @car_year_model" do
        CarYearModel.stub(:find) { mock_car_year_model(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:car_year_model).should be(mock_car_year_model)
      end

      it "redirects to the car_year_model" do
        CarYearModel.stub(:find) { mock_car_year_model(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(car_year_model_url(mock_car_year_model))
      end
    end

    describe "with invalid params" do
      it "assigns the car_year_model as @car_year_model" do
        CarYearModel.stub(:find) { mock_car_year_model(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:car_year_model).should be(mock_car_year_model)
      end

      it "re-renders the 'edit' template" do
        CarYearModel.stub(:find) { mock_car_year_model(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_year_model" do
      CarYearModel.stub(:find).with("37") { mock_car_year_model }
      mock_car_year_model.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the car_year_models list" do
      CarYearModel.stub(:find) { mock_car_year_model }
      delete :destroy, :id => "1"
      response.should redirect_to(car_year_models_url)
    end
  end

end
