require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanDeadWeightsController do

  def mock_caravan_dead_weight(stubs={})
    @mock_caravan_dead_weight ||= mock_model(CaravanDeadWeight, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_dead_weights as @caravan_dead_weights" do
      CaravanDeadWeight.stub(:all) { [mock_caravan_dead_weight] }
      get :index
      assigns(:caravan_dead_weights).should eq([mock_caravan_dead_weight])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_dead_weight as @caravan_dead_weight" do
      CaravanDeadWeight.stub(:find).with("37") { mock_caravan_dead_weight }
      get :show, :id => "37"
      assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_dead_weight as @caravan_dead_weight" do
      CaravanDeadWeight.stub(:new) { mock_caravan_dead_weight }
      get :new
      assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_dead_weight as @caravan_dead_weight" do
      CaravanDeadWeight.stub(:find).with("37") { mock_caravan_dead_weight }
      get :edit, :id => "37"
      assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_dead_weight as @caravan_dead_weight" do
        CaravanDeadWeight.stub(:new).with({'these' => 'params'}) { mock_caravan_dead_weight(:save => true) }
        post :create, :caravan_dead_weight => {'these' => 'params'}
        assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
      end

      it "redirects to the created caravan_dead_weight" do
        CaravanDeadWeight.stub(:new) { mock_caravan_dead_weight(:save => true) }
        post :create, :caravan_dead_weight => {}
        response.should redirect_to(caravan_dead_weight_url(mock_caravan_dead_weight))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_dead_weight as @caravan_dead_weight" do
        CaravanDeadWeight.stub(:new).with({'these' => 'params'}) { mock_caravan_dead_weight(:save => false) }
        post :create, :caravan_dead_weight => {'these' => 'params'}
        assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
      end

      it "re-renders the 'new' template" do
        CaravanDeadWeight.stub(:new) { mock_caravan_dead_weight(:save => false) }
        post :create, :caravan_dead_weight => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_dead_weight" do
        CaravanDeadWeight.stub(:find).with("37") { mock_caravan_dead_weight }
        mock_caravan_dead_weight.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_dead_weight => {'these' => 'params'}
      end

      it "assigns the requested caravan_dead_weight as @caravan_dead_weight" do
        CaravanDeadWeight.stub(:find) { mock_caravan_dead_weight(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
      end

      it "redirects to the caravan_dead_weight" do
        CaravanDeadWeight.stub(:find) { mock_caravan_dead_weight(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_dead_weight_url(mock_caravan_dead_weight))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_dead_weight as @caravan_dead_weight" do
        CaravanDeadWeight.stub(:find) { mock_caravan_dead_weight(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_dead_weight).should be(mock_caravan_dead_weight)
      end

      it "re-renders the 'edit' template" do
        CaravanDeadWeight.stub(:find) { mock_caravan_dead_weight(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_dead_weight" do
      CaravanDeadWeight.stub(:find).with("37") { mock_caravan_dead_weight }
      mock_caravan_dead_weight.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_dead_weights list" do
      CaravanDeadWeight.stub(:find) { mock_caravan_dead_weight }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_dead_weights_url)
    end
  end

end
