require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanGrossWeightsController do

  def mock_caravan_gross_weight(stubs={})
    @mock_caravan_gross_weight ||= mock_model(CaravanGrossWeight, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_gross_weights as @caravan_gross_weights" do
      CaravanGrossWeight.stub(:all) { [mock_caravan_gross_weight] }
      get :index
      assigns(:caravan_gross_weights).should eq([mock_caravan_gross_weight])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_gross_weight as @caravan_gross_weight" do
      CaravanGrossWeight.stub(:find).with("37") { mock_caravan_gross_weight }
      get :show, :id => "37"
      assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_gross_weight as @caravan_gross_weight" do
      CaravanGrossWeight.stub(:new) { mock_caravan_gross_weight }
      get :new
      assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_gross_weight as @caravan_gross_weight" do
      CaravanGrossWeight.stub(:find).with("37") { mock_caravan_gross_weight }
      get :edit, :id => "37"
      assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_gross_weight as @caravan_gross_weight" do
        CaravanGrossWeight.stub(:new).with({'these' => 'params'}) { mock_caravan_gross_weight(:save => true) }
        post :create, :caravan_gross_weight => {'these' => 'params'}
        assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
      end

      it "redirects to the created caravan_gross_weight" do
        CaravanGrossWeight.stub(:new) { mock_caravan_gross_weight(:save => true) }
        post :create, :caravan_gross_weight => {}
        response.should redirect_to(caravan_gross_weight_url(mock_caravan_gross_weight))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_gross_weight as @caravan_gross_weight" do
        CaravanGrossWeight.stub(:new).with({'these' => 'params'}) { mock_caravan_gross_weight(:save => false) }
        post :create, :caravan_gross_weight => {'these' => 'params'}
        assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
      end

      it "re-renders the 'new' template" do
        CaravanGrossWeight.stub(:new) { mock_caravan_gross_weight(:save => false) }
        post :create, :caravan_gross_weight => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_gross_weight" do
        CaravanGrossWeight.stub(:find).with("37") { mock_caravan_gross_weight }
        mock_caravan_gross_weight.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_gross_weight => {'these' => 'params'}
      end

      it "assigns the requested caravan_gross_weight as @caravan_gross_weight" do
        CaravanGrossWeight.stub(:find) { mock_caravan_gross_weight(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
      end

      it "redirects to the caravan_gross_weight" do
        CaravanGrossWeight.stub(:find) { mock_caravan_gross_weight(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_gross_weight_url(mock_caravan_gross_weight))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_gross_weight as @caravan_gross_weight" do
        CaravanGrossWeight.stub(:find) { mock_caravan_gross_weight(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_gross_weight).should be(mock_caravan_gross_weight)
      end

      it "re-renders the 'edit' template" do
        CaravanGrossWeight.stub(:find) { mock_caravan_gross_weight(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_gross_weight" do
      CaravanGrossWeight.stub(:find).with("37") { mock_caravan_gross_weight }
      mock_caravan_gross_weight.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_gross_weights list" do
      CaravanGrossWeight.stub(:find) { mock_caravan_gross_weight }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_gross_weights_url)
    end
  end

end
