require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanUserNamesController do

  def mock_caravan_user_name(stubs={})
    @mock_caravan_user_name ||= mock_model(CaravanUserName, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_user_names as @caravan_user_names" do
      CaravanUserName.stub(:all) { [mock_caravan_user_name] }
      get :index
      assigns(:caravan_user_names).should eq([mock_caravan_user_name])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_user_name as @caravan_user_name" do
      CaravanUserName.stub(:find).with("37") { mock_caravan_user_name }
      get :show, :id => "37"
      assigns(:caravan_user_name).should be(mock_caravan_user_name)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_user_name as @caravan_user_name" do
      CaravanUserName.stub(:new) { mock_caravan_user_name }
      get :new
      assigns(:caravan_user_name).should be(mock_caravan_user_name)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_user_name as @caravan_user_name" do
      CaravanUserName.stub(:find).with("37") { mock_caravan_user_name }
      get :edit, :id => "37"
      assigns(:caravan_user_name).should be(mock_caravan_user_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_user_name as @caravan_user_name" do
        CaravanUserName.stub(:new).with({'these' => 'params'}) { mock_caravan_user_name(:save => true) }
        post :create, :caravan_user_name => {'these' => 'params'}
        assigns(:caravan_user_name).should be(mock_caravan_user_name)
      end

      it "redirects to the created caravan_user_name" do
        CaravanUserName.stub(:new) { mock_caravan_user_name(:save => true) }
        post :create, :caravan_user_name => {}
        response.should redirect_to(caravan_user_name_url(mock_caravan_user_name))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_user_name as @caravan_user_name" do
        CaravanUserName.stub(:new).with({'these' => 'params'}) { mock_caravan_user_name(:save => false) }
        post :create, :caravan_user_name => {'these' => 'params'}
        assigns(:caravan_user_name).should be(mock_caravan_user_name)
      end

      it "re-renders the 'new' template" do
        CaravanUserName.stub(:new) { mock_caravan_user_name(:save => false) }
        post :create, :caravan_user_name => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_user_name" do
        CaravanUserName.stub(:find).with("37") { mock_caravan_user_name }
        mock_caravan_user_name.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_user_name => {'these' => 'params'}
      end

      it "assigns the requested caravan_user_name as @caravan_user_name" do
        CaravanUserName.stub(:find) { mock_caravan_user_name(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_user_name).should be(mock_caravan_user_name)
      end

      it "redirects to the caravan_user_name" do
        CaravanUserName.stub(:find) { mock_caravan_user_name(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_user_name_url(mock_caravan_user_name))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_user_name as @caravan_user_name" do
        CaravanUserName.stub(:find) { mock_caravan_user_name(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_user_name).should be(mock_caravan_user_name)
      end

      it "re-renders the 'edit' template" do
        CaravanUserName.stub(:find) { mock_caravan_user_name(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_user_name" do
      CaravanUserName.stub(:find).with("37") { mock_caravan_user_name }
      mock_caravan_user_name.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_user_names list" do
      CaravanUserName.stub(:find) { mock_caravan_user_name }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_user_names_url)
    end
  end

end
