require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanTotalOwnersController do

  def mock_caravan_total_owner(stubs={})
    @mock_caravan_total_owner ||= mock_model(CaravanTotalOwner, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_total_owners as @caravan_total_owners" do
      CaravanTotalOwner.stub(:all) { [mock_caravan_total_owner] }
      get :index
      assigns(:caravan_total_owners).should eq([mock_caravan_total_owner])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_total_owner as @caravan_total_owner" do
      CaravanTotalOwner.stub(:find).with("37") { mock_caravan_total_owner }
      get :show, :id => "37"
      assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_total_owner as @caravan_total_owner" do
      CaravanTotalOwner.stub(:new) { mock_caravan_total_owner }
      get :new
      assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_total_owner as @caravan_total_owner" do
      CaravanTotalOwner.stub(:find).with("37") { mock_caravan_total_owner }
      get :edit, :id => "37"
      assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_total_owner as @caravan_total_owner" do
        CaravanTotalOwner.stub(:new).with({'these' => 'params'}) { mock_caravan_total_owner(:save => true) }
        post :create, :caravan_total_owner => {'these' => 'params'}
        assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
      end

      it "redirects to the created caravan_total_owner" do
        CaravanTotalOwner.stub(:new) { mock_caravan_total_owner(:save => true) }
        post :create, :caravan_total_owner => {}
        response.should redirect_to(caravan_total_owner_url(mock_caravan_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_total_owner as @caravan_total_owner" do
        CaravanTotalOwner.stub(:new).with({'these' => 'params'}) { mock_caravan_total_owner(:save => false) }
        post :create, :caravan_total_owner => {'these' => 'params'}
        assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
      end

      it "re-renders the 'new' template" do
        CaravanTotalOwner.stub(:new) { mock_caravan_total_owner(:save => false) }
        post :create, :caravan_total_owner => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_total_owner" do
        CaravanTotalOwner.stub(:find).with("37") { mock_caravan_total_owner }
        mock_caravan_total_owner.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_total_owner => {'these' => 'params'}
      end

      it "assigns the requested caravan_total_owner as @caravan_total_owner" do
        CaravanTotalOwner.stub(:find) { mock_caravan_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
      end

      it "redirects to the caravan_total_owner" do
        CaravanTotalOwner.stub(:find) { mock_caravan_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_total_owner_url(mock_caravan_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_total_owner as @caravan_total_owner" do
        CaravanTotalOwner.stub(:find) { mock_caravan_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_total_owner).should be(mock_caravan_total_owner)
      end

      it "re-renders the 'edit' template" do
        CaravanTotalOwner.stub(:find) { mock_caravan_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_total_owner" do
      CaravanTotalOwner.stub(:find).with("37") { mock_caravan_total_owner }
      mock_caravan_total_owner.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_total_owners list" do
      CaravanTotalOwner.stub(:find) { mock_caravan_total_owner }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_total_owners_url)
    end
  end

end
