require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanPostsController do

  def mock_caravan_post(stubs={})
    @mock_caravan_post ||= mock_model(CaravanPost, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_posts as @caravan_posts" do
      CaravanPost.stub(:all) { [mock_caravan_post] }
      get :index
      assigns(:caravan_posts).should eq([mock_caravan_post])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_post as @caravan_post" do
      CaravanPost.stub(:find).with("37") { mock_caravan_post }
      get :show, :id => "37"
      assigns(:caravan_post).should be(mock_caravan_post)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_post as @caravan_post" do
      CaravanPost.stub(:new) { mock_caravan_post }
      get :new
      assigns(:caravan_post).should be(mock_caravan_post)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_post as @caravan_post" do
      CaravanPost.stub(:find).with("37") { mock_caravan_post }
      get :edit, :id => "37"
      assigns(:caravan_post).should be(mock_caravan_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_post as @caravan_post" do
        CaravanPost.stub(:new).with({'these' => 'params'}) { mock_caravan_post(:save => true) }
        post :create, :caravan_post => {'these' => 'params'}
        assigns(:caravan_post).should be(mock_caravan_post)
      end

      it "redirects to the created caravan_post" do
        CaravanPost.stub(:new) { mock_caravan_post(:save => true) }
        post :create, :caravan_post => {}
        response.should redirect_to(caravan_post_url(mock_caravan_post))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_post as @caravan_post" do
        CaravanPost.stub(:new).with({'these' => 'params'}) { mock_caravan_post(:save => false) }
        post :create, :caravan_post => {'these' => 'params'}
        assigns(:caravan_post).should be(mock_caravan_post)
      end

      it "re-renders the 'new' template" do
        CaravanPost.stub(:new) { mock_caravan_post(:save => false) }
        post :create, :caravan_post => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_post" do
        CaravanPost.stub(:find).with("37") { mock_caravan_post }
        mock_caravan_post.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_post => {'these' => 'params'}
      end

      it "assigns the requested caravan_post as @caravan_post" do
        CaravanPost.stub(:find) { mock_caravan_post(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_post).should be(mock_caravan_post)
      end

      it "redirects to the caravan_post" do
        CaravanPost.stub(:find) { mock_caravan_post(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_post_url(mock_caravan_post))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_post as @caravan_post" do
        CaravanPost.stub(:find) { mock_caravan_post(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_post).should be(mock_caravan_post)
      end

      it "re-renders the 'edit' template" do
        CaravanPost.stub(:find) { mock_caravan_post(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_post" do
      CaravanPost.stub(:find).with("37") { mock_caravan_post }
      mock_caravan_post.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_posts list" do
      CaravanPost.stub(:find) { mock_caravan_post }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_posts_url)
    end
  end

end
