require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanModelSectionsController do

  def mock_caravan_model_section(stubs={})
    @mock_caravan_model_section ||= mock_model(CaravanModelSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_model_sections as @caravan_model_sections" do
      CaravanModelSection.stub(:all) { [mock_caravan_model_section] }
      get :index
      assigns(:caravan_model_sections).should eq([mock_caravan_model_section])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_model_section as @caravan_model_section" do
      CaravanModelSection.stub(:find).with("37") { mock_caravan_model_section }
      get :show, :id => "37"
      assigns(:caravan_model_section).should be(mock_caravan_model_section)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_model_section as @caravan_model_section" do
      CaravanModelSection.stub(:new) { mock_caravan_model_section }
      get :new
      assigns(:caravan_model_section).should be(mock_caravan_model_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_model_section as @caravan_model_section" do
      CaravanModelSection.stub(:find).with("37") { mock_caravan_model_section }
      get :edit, :id => "37"
      assigns(:caravan_model_section).should be(mock_caravan_model_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_model_section as @caravan_model_section" do
        CaravanModelSection.stub(:new).with({'these' => 'params'}) { mock_caravan_model_section(:save => true) }
        post :create, :caravan_model_section => {'these' => 'params'}
        assigns(:caravan_model_section).should be(mock_caravan_model_section)
      end

      it "redirects to the created caravan_model_section" do
        CaravanModelSection.stub(:new) { mock_caravan_model_section(:save => true) }
        post :create, :caravan_model_section => {}
        response.should redirect_to(caravan_model_section_url(mock_caravan_model_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_model_section as @caravan_model_section" do
        CaravanModelSection.stub(:new).with({'these' => 'params'}) { mock_caravan_model_section(:save => false) }
        post :create, :caravan_model_section => {'these' => 'params'}
        assigns(:caravan_model_section).should be(mock_caravan_model_section)
      end

      it "re-renders the 'new' template" do
        CaravanModelSection.stub(:new) { mock_caravan_model_section(:save => false) }
        post :create, :caravan_model_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_model_section" do
        CaravanModelSection.stub(:find).with("37") { mock_caravan_model_section }
        mock_caravan_model_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_model_section => {'these' => 'params'}
      end

      it "assigns the requested caravan_model_section as @caravan_model_section" do
        CaravanModelSection.stub(:find) { mock_caravan_model_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_model_section).should be(mock_caravan_model_section)
      end

      it "redirects to the caravan_model_section" do
        CaravanModelSection.stub(:find) { mock_caravan_model_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_model_section_url(mock_caravan_model_section))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_model_section as @caravan_model_section" do
        CaravanModelSection.stub(:find) { mock_caravan_model_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_model_section).should be(mock_caravan_model_section)
      end

      it "re-renders the 'edit' template" do
        CaravanModelSection.stub(:find) { mock_caravan_model_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_model_section" do
      CaravanModelSection.stub(:find).with("37") { mock_caravan_model_section }
      mock_caravan_model_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_model_sections list" do
      CaravanModelSection.stub(:find) { mock_caravan_model_section }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_model_sections_url)
    end
  end

end
