require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanMileagesController do

  def mock_caravan_mileage(stubs={})
    @mock_caravan_mileage ||= mock_model(CaravanMileage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_mileages as @caravan_mileages" do
      CaravanMileage.stub(:all) { [mock_caravan_mileage] }
      get :index
      assigns(:caravan_mileages).should eq([mock_caravan_mileage])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_mileage as @caravan_mileage" do
      CaravanMileage.stub(:find).with("37") { mock_caravan_mileage }
      get :show, :id => "37"
      assigns(:caravan_mileage).should be(mock_caravan_mileage)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_mileage as @caravan_mileage" do
      CaravanMileage.stub(:new) { mock_caravan_mileage }
      get :new
      assigns(:caravan_mileage).should be(mock_caravan_mileage)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_mileage as @caravan_mileage" do
      CaravanMileage.stub(:find).with("37") { mock_caravan_mileage }
      get :edit, :id => "37"
      assigns(:caravan_mileage).should be(mock_caravan_mileage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_mileage as @caravan_mileage" do
        CaravanMileage.stub(:new).with({'these' => 'params'}) { mock_caravan_mileage(:save => true) }
        post :create, :caravan_mileage => {'these' => 'params'}
        assigns(:caravan_mileage).should be(mock_caravan_mileage)
      end

      it "redirects to the created caravan_mileage" do
        CaravanMileage.stub(:new) { mock_caravan_mileage(:save => true) }
        post :create, :caravan_mileage => {}
        response.should redirect_to(caravan_mileage_url(mock_caravan_mileage))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_mileage as @caravan_mileage" do
        CaravanMileage.stub(:new).with({'these' => 'params'}) { mock_caravan_mileage(:save => false) }
        post :create, :caravan_mileage => {'these' => 'params'}
        assigns(:caravan_mileage).should be(mock_caravan_mileage)
      end

      it "re-renders the 'new' template" do
        CaravanMileage.stub(:new) { mock_caravan_mileage(:save => false) }
        post :create, :caravan_mileage => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_mileage" do
        CaravanMileage.stub(:find).with("37") { mock_caravan_mileage }
        mock_caravan_mileage.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_mileage => {'these' => 'params'}
      end

      it "assigns the requested caravan_mileage as @caravan_mileage" do
        CaravanMileage.stub(:find) { mock_caravan_mileage(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_mileage).should be(mock_caravan_mileage)
      end

      it "redirects to the caravan_mileage" do
        CaravanMileage.stub(:find) { mock_caravan_mileage(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_mileage_url(mock_caravan_mileage))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_mileage as @caravan_mileage" do
        CaravanMileage.stub(:find) { mock_caravan_mileage(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_mileage).should be(mock_caravan_mileage)
      end

      it "re-renders the 'edit' template" do
        CaravanMileage.stub(:find) { mock_caravan_mileage(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_mileage" do
      CaravanMileage.stub(:find).with("37") { mock_caravan_mileage }
      mock_caravan_mileage.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_mileages list" do
      CaravanMileage.stub(:find) { mock_caravan_mileage }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_mileages_url)
    end
  end

end
