require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CaravanDomicileTypesController do

  def mock_caravan_domicile_type(stubs={})
    @mock_caravan_domicile_type ||= mock_model(CaravanDomicileType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all caravan_domicile_types as @caravan_domicile_types" do
      CaravanDomicileType.stub(:all) { [mock_caravan_domicile_type] }
      get :index
      assigns(:caravan_domicile_types).should eq([mock_caravan_domicile_type])
    end
  end

  describe "GET show" do
    it "assigns the requested caravan_domicile_type as @caravan_domicile_type" do
      CaravanDomicileType.stub(:find).with("37") { mock_caravan_domicile_type }
      get :show, :id => "37"
      assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
    end
  end

  describe "GET new" do
    it "assigns a new caravan_domicile_type as @caravan_domicile_type" do
      CaravanDomicileType.stub(:new) { mock_caravan_domicile_type }
      get :new
      assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested caravan_domicile_type as @caravan_domicile_type" do
      CaravanDomicileType.stub(:find).with("37") { mock_caravan_domicile_type }
      get :edit, :id => "37"
      assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created caravan_domicile_type as @caravan_domicile_type" do
        CaravanDomicileType.stub(:new).with({'these' => 'params'}) { mock_caravan_domicile_type(:save => true) }
        post :create, :caravan_domicile_type => {'these' => 'params'}
        assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
      end

      it "redirects to the created caravan_domicile_type" do
        CaravanDomicileType.stub(:new) { mock_caravan_domicile_type(:save => true) }
        post :create, :caravan_domicile_type => {}
        response.should redirect_to(caravan_domicile_type_url(mock_caravan_domicile_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved caravan_domicile_type as @caravan_domicile_type" do
        CaravanDomicileType.stub(:new).with({'these' => 'params'}) { mock_caravan_domicile_type(:save => false) }
        post :create, :caravan_domicile_type => {'these' => 'params'}
        assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
      end

      it "re-renders the 'new' template" do
        CaravanDomicileType.stub(:new) { mock_caravan_domicile_type(:save => false) }
        post :create, :caravan_domicile_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested caravan_domicile_type" do
        CaravanDomicileType.stub(:find).with("37") { mock_caravan_domicile_type }
        mock_caravan_domicile_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :caravan_domicile_type => {'these' => 'params'}
      end

      it "assigns the requested caravan_domicile_type as @caravan_domicile_type" do
        CaravanDomicileType.stub(:find) { mock_caravan_domicile_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
      end

      it "redirects to the caravan_domicile_type" do
        CaravanDomicileType.stub(:find) { mock_caravan_domicile_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(caravan_domicile_type_url(mock_caravan_domicile_type))
      end
    end

    describe "with invalid params" do
      it "assigns the caravan_domicile_type as @caravan_domicile_type" do
        CaravanDomicileType.stub(:find) { mock_caravan_domicile_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:caravan_domicile_type).should be(mock_caravan_domicile_type)
      end

      it "re-renders the 'edit' template" do
        CaravanDomicileType.stub(:find) { mock_caravan_domicile_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested caravan_domicile_type" do
      CaravanDomicileType.stub(:find).with("37") { mock_caravan_domicile_type }
      mock_caravan_domicile_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the caravan_domicile_types list" do
      CaravanDomicileType.stub(:find) { mock_caravan_domicile_type }
      delete :destroy, :id => "1"
      response.should redirect_to(caravan_domicile_types_url)
    end
  end

end
