require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ColorTypesController do

  def mock_color_type(stubs={})
    @mock_color_type ||= mock_model(ColorType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all color_types as @color_types" do
      ColorType.stub(:all) { [mock_color_type] }
      get :index
      assigns(:color_types).should eq([mock_color_type])
    end
  end

  describe "GET show" do
    it "assigns the requested color_type as @color_type" do
      ColorType.stub(:find).with("37") { mock_color_type }
      get :show, :id => "37"
      assigns(:color_type).should be(mock_color_type)
    end
  end

  describe "GET new" do
    it "assigns a new color_type as @color_type" do
      ColorType.stub(:new) { mock_color_type }
      get :new
      assigns(:color_type).should be(mock_color_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested color_type as @color_type" do
      ColorType.stub(:find).with("37") { mock_color_type }
      get :edit, :id => "37"
      assigns(:color_type).should be(mock_color_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created color_type as @color_type" do
        ColorType.stub(:new).with({'these' => 'params'}) { mock_color_type(:save => true) }
        post :create, :color_type => {'these' => 'params'}
        assigns(:color_type).should be(mock_color_type)
      end

      it "redirects to the created color_type" do
        ColorType.stub(:new) { mock_color_type(:save => true) }
        post :create, :color_type => {}
        response.should redirect_to(color_type_url(mock_color_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved color_type as @color_type" do
        ColorType.stub(:new).with({'these' => 'params'}) { mock_color_type(:save => false) }
        post :create, :color_type => {'these' => 'params'}
        assigns(:color_type).should be(mock_color_type)
      end

      it "re-renders the 'new' template" do
        ColorType.stub(:new) { mock_color_type(:save => false) }
        post :create, :color_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested color_type" do
        ColorType.stub(:find).with("37") { mock_color_type }
        mock_color_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :color_type => {'these' => 'params'}
      end

      it "assigns the requested color_type as @color_type" do
        ColorType.stub(:find) { mock_color_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:color_type).should be(mock_color_type)
      end

      it "redirects to the color_type" do
        ColorType.stub(:find) { mock_color_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(color_type_url(mock_color_type))
      end
    end

    describe "with invalid params" do
      it "assigns the color_type as @color_type" do
        ColorType.stub(:find) { mock_color_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:color_type).should be(mock_color_type)
      end

      it "re-renders the 'edit' template" do
        ColorType.stub(:find) { mock_color_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested color_type" do
      ColorType.stub(:find).with("37") { mock_color_type }
      mock_color_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the color_types list" do
      ColorType.stub(:find) { mock_color_type }
      delete :destroy, :id => "1"
      response.should redirect_to(color_types_url)
    end
  end

end
