require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CoverImageUidsController do

  def mock_cover_image_uid(stubs={})
    @mock_cover_image_uid ||= mock_model(CoverImageUid, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cover_image_uids as @cover_image_uids" do
      CoverImageUid.stub(:all) { [mock_cover_image_uid] }
      get :index
      assigns(:cover_image_uids).should eq([mock_cover_image_uid])
    end
  end

  describe "GET show" do
    it "assigns the requested cover_image_uid as @cover_image_uid" do
      CoverImageUid.stub(:find).with("37") { mock_cover_image_uid }
      get :show, :id => "37"
      assigns(:cover_image_uid).should be(mock_cover_image_uid)
    end
  end

  describe "GET new" do
    it "assigns a new cover_image_uid as @cover_image_uid" do
      CoverImageUid.stub(:new) { mock_cover_image_uid }
      get :new
      assigns(:cover_image_uid).should be(mock_cover_image_uid)
    end
  end

  describe "GET edit" do
    it "assigns the requested cover_image_uid as @cover_image_uid" do
      CoverImageUid.stub(:find).with("37") { mock_cover_image_uid }
      get :edit, :id => "37"
      assigns(:cover_image_uid).should be(mock_cover_image_uid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cover_image_uid as @cover_image_uid" do
        CoverImageUid.stub(:new).with({'these' => 'params'}) { mock_cover_image_uid(:save => true) }
        post :create, :cover_image_uid => {'these' => 'params'}
        assigns(:cover_image_uid).should be(mock_cover_image_uid)
      end

      it "redirects to the created cover_image_uid" do
        CoverImageUid.stub(:new) { mock_cover_image_uid(:save => true) }
        post :create, :cover_image_uid => {}
        response.should redirect_to(cover_image_uid_url(mock_cover_image_uid))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cover_image_uid as @cover_image_uid" do
        CoverImageUid.stub(:new).with({'these' => 'params'}) { mock_cover_image_uid(:save => false) }
        post :create, :cover_image_uid => {'these' => 'params'}
        assigns(:cover_image_uid).should be(mock_cover_image_uid)
      end

      it "re-renders the 'new' template" do
        CoverImageUid.stub(:new) { mock_cover_image_uid(:save => false) }
        post :create, :cover_image_uid => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cover_image_uid" do
        CoverImageUid.stub(:find).with("37") { mock_cover_image_uid }
        mock_cover_image_uid.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cover_image_uid => {'these' => 'params'}
      end

      it "assigns the requested cover_image_uid as @cover_image_uid" do
        CoverImageUid.stub(:find) { mock_cover_image_uid(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cover_image_uid).should be(mock_cover_image_uid)
      end

      it "redirects to the cover_image_uid" do
        CoverImageUid.stub(:find) { mock_cover_image_uid(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cover_image_uid_url(mock_cover_image_uid))
      end
    end

    describe "with invalid params" do
      it "assigns the cover_image_uid as @cover_image_uid" do
        CoverImageUid.stub(:find) { mock_cover_image_uid(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cover_image_uid).should be(mock_cover_image_uid)
      end

      it "re-renders the 'edit' template" do
        CoverImageUid.stub(:find) { mock_cover_image_uid(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cover_image_uid" do
      CoverImageUid.stub(:find).with("37") { mock_cover_image_uid }
      mock_cover_image_uid.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cover_image_uids list" do
      CoverImageUid.stub(:find) { mock_cover_image_uid }
      delete :destroy, :id => "1"
      response.should redirect_to(cover_image_uids_url)
    end
  end

end
