require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DomicileTypesController do

  def mock_domicile_type(stubs={})
    @mock_domicile_type ||= mock_model(DomicileType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all domicile_types as @domicile_types" do
      DomicileType.stub(:all) { [mock_domicile_type] }
      get :index
      assigns(:domicile_types).should eq([mock_domicile_type])
    end
  end

  describe "GET show" do
    it "assigns the requested domicile_type as @domicile_type" do
      DomicileType.stub(:find).with("37") { mock_domicile_type }
      get :show, :id => "37"
      assigns(:domicile_type).should be(mock_domicile_type)
    end
  end

  describe "GET new" do
    it "assigns a new domicile_type as @domicile_type" do
      DomicileType.stub(:new) { mock_domicile_type }
      get :new
      assigns(:domicile_type).should be(mock_domicile_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested domicile_type as @domicile_type" do
      DomicileType.stub(:find).with("37") { mock_domicile_type }
      get :edit, :id => "37"
      assigns(:domicile_type).should be(mock_domicile_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created domicile_type as @domicile_type" do
        DomicileType.stub(:new).with({'these' => 'params'}) { mock_domicile_type(:save => true) }
        post :create, :domicile_type => {'these' => 'params'}
        assigns(:domicile_type).should be(mock_domicile_type)
      end

      it "redirects to the created domicile_type" do
        DomicileType.stub(:new) { mock_domicile_type(:save => true) }
        post :create, :domicile_type => {}
        response.should redirect_to(domicile_type_url(mock_domicile_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved domicile_type as @domicile_type" do
        DomicileType.stub(:new).with({'these' => 'params'}) { mock_domicile_type(:save => false) }
        post :create, :domicile_type => {'these' => 'params'}
        assigns(:domicile_type).should be(mock_domicile_type)
      end

      it "re-renders the 'new' template" do
        DomicileType.stub(:new) { mock_domicile_type(:save => false) }
        post :create, :domicile_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested domicile_type" do
        DomicileType.stub(:find).with("37") { mock_domicile_type }
        mock_domicile_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :domicile_type => {'these' => 'params'}
      end

      it "assigns the requested domicile_type as @domicile_type" do
        DomicileType.stub(:find) { mock_domicile_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:domicile_type).should be(mock_domicile_type)
      end

      it "redirects to the domicile_type" do
        DomicileType.stub(:find) { mock_domicile_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(domicile_type_url(mock_domicile_type))
      end
    end

    describe "with invalid params" do
      it "assigns the domicile_type as @domicile_type" do
        DomicileType.stub(:find) { mock_domicile_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:domicile_type).should be(mock_domicile_type)
      end

      it "re-renders the 'edit' template" do
        DomicileType.stub(:find) { mock_domicile_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested domicile_type" do
      DomicileType.stub(:find).with("37") { mock_domicile_type }
      mock_domicile_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the domicile_types list" do
      DomicileType.stub(:find) { mock_domicile_type }
      delete :destroy, :id => "1"
      response.should redirect_to(domicile_types_url)
    end
  end

end
