require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DraughtsController do

  def mock_draught(stubs={})
    @mock_draught ||= mock_model(Draught, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all draughts as @draughts" do
      Draught.stub(:all) { [mock_draught] }
      get :index
      assigns(:draughts).should eq([mock_draught])
    end
  end

  describe "GET show" do
    it "assigns the requested draught as @draught" do
      Draught.stub(:find).with("37") { mock_draught }
      get :show, :id => "37"
      assigns(:draught).should be(mock_draught)
    end
  end

  describe "GET new" do
    it "assigns a new draught as @draught" do
      Draught.stub(:new) { mock_draught }
      get :new
      assigns(:draught).should be(mock_draught)
    end
  end

  describe "GET edit" do
    it "assigns the requested draught as @draught" do
      Draught.stub(:find).with("37") { mock_draught }
      get :edit, :id => "37"
      assigns(:draught).should be(mock_draught)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created draught as @draught" do
        Draught.stub(:new).with({'these' => 'params'}) { mock_draught(:save => true) }
        post :create, :draught => {'these' => 'params'}
        assigns(:draught).should be(mock_draught)
      end

      it "redirects to the created draught" do
        Draught.stub(:new) { mock_draught(:save => true) }
        post :create, :draught => {}
        response.should redirect_to(draught_url(mock_draught))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved draught as @draught" do
        Draught.stub(:new).with({'these' => 'params'}) { mock_draught(:save => false) }
        post :create, :draught => {'these' => 'params'}
        assigns(:draught).should be(mock_draught)
      end

      it "re-renders the 'new' template" do
        Draught.stub(:new) { mock_draught(:save => false) }
        post :create, :draught => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested draught" do
        Draught.stub(:find).with("37") { mock_draught }
        mock_draught.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :draught => {'these' => 'params'}
      end

      it "assigns the requested draught as @draught" do
        Draught.stub(:find) { mock_draught(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:draught).should be(mock_draught)
      end

      it "redirects to the draught" do
        Draught.stub(:find) { mock_draught(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(draught_url(mock_draught))
      end
    end

    describe "with invalid params" do
      it "assigns the draught as @draught" do
        Draught.stub(:find) { mock_draught(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:draught).should be(mock_draught)
      end

      it "re-renders the 'edit' template" do
        Draught.stub(:find) { mock_draught(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested draught" do
      Draught.stub(:find).with("37") { mock_draught }
      mock_draught.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the draughts list" do
      Draught.stub(:find) { mock_draught }
      delete :destroy, :id => "1"
      response.should redirect_to(draughts_url)
    end
  end

end
