require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DriveTypesController do

  def mock_drive_type(stubs={})
    @mock_drive_type ||= mock_model(DriveType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all drive_types as @drive_types" do
      DriveType.stub(:all) { [mock_drive_type] }
      get :index
      assigns(:drive_types).should eq([mock_drive_type])
    end
  end

  describe "GET show" do
    it "assigns the requested drive_type as @drive_type" do
      DriveType.stub(:find).with("37") { mock_drive_type }
      get :show, :id => "37"
      assigns(:drive_type).should be(mock_drive_type)
    end
  end

  describe "GET new" do
    it "assigns a new drive_type as @drive_type" do
      DriveType.stub(:new) { mock_drive_type }
      get :new
      assigns(:drive_type).should be(mock_drive_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested drive_type as @drive_type" do
      DriveType.stub(:find).with("37") { mock_drive_type }
      get :edit, :id => "37"
      assigns(:drive_type).should be(mock_drive_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created drive_type as @drive_type" do
        DriveType.stub(:new).with({'these' => 'params'}) { mock_drive_type(:save => true) }
        post :create, :drive_type => {'these' => 'params'}
        assigns(:drive_type).should be(mock_drive_type)
      end

      it "redirects to the created drive_type" do
        DriveType.stub(:new) { mock_drive_type(:save => true) }
        post :create, :drive_type => {}
        response.should redirect_to(drive_type_url(mock_drive_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drive_type as @drive_type" do
        DriveType.stub(:new).with({'these' => 'params'}) { mock_drive_type(:save => false) }
        post :create, :drive_type => {'these' => 'params'}
        assigns(:drive_type).should be(mock_drive_type)
      end

      it "re-renders the 'new' template" do
        DriveType.stub(:new) { mock_drive_type(:save => false) }
        post :create, :drive_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drive_type" do
        DriveType.stub(:find).with("37") { mock_drive_type }
        mock_drive_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :drive_type => {'these' => 'params'}
      end

      it "assigns the requested drive_type as @drive_type" do
        DriveType.stub(:find) { mock_drive_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:drive_type).should be(mock_drive_type)
      end

      it "redirects to the drive_type" do
        DriveType.stub(:find) { mock_drive_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(drive_type_url(mock_drive_type))
      end
    end

    describe "with invalid params" do
      it "assigns the drive_type as @drive_type" do
        DriveType.stub(:find) { mock_drive_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:drive_type).should be(mock_drive_type)
      end

      it "re-renders the 'edit' template" do
        DriveType.stub(:find) { mock_drive_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drive_type" do
      DriveType.stub(:find).with("37") { mock_drive_type }
      mock_drive_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the drive_types list" do
      DriveType.stub(:find) { mock_drive_type }
      delete :destroy, :id => "1"
      response.should redirect_to(drive_types_url)
    end
  end

end
