require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FuelTypesController do

  def mock_fuel_type(stubs={})
    @mock_fuel_type ||= mock_model(FuelType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all fuel_types as @fuel_types" do
      FuelType.stub(:all) { [mock_fuel_type] }
      get :index
      assigns(:fuel_types).should eq([mock_fuel_type])
    end
  end

  describe "GET show" do
    it "assigns the requested fuel_type as @fuel_type" do
      FuelType.stub(:find).with("37") { mock_fuel_type }
      get :show, :id => "37"
      assigns(:fuel_type).should be(mock_fuel_type)
    end
  end

  describe "GET new" do
    it "assigns a new fuel_type as @fuel_type" do
      FuelType.stub(:new) { mock_fuel_type }
      get :new
      assigns(:fuel_type).should be(mock_fuel_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested fuel_type as @fuel_type" do
      FuelType.stub(:find).with("37") { mock_fuel_type }
      get :edit, :id => "37"
      assigns(:fuel_type).should be(mock_fuel_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created fuel_type as @fuel_type" do
        FuelType.stub(:new).with({'these' => 'params'}) { mock_fuel_type(:save => true) }
        post :create, :fuel_type => {'these' => 'params'}
        assigns(:fuel_type).should be(mock_fuel_type)
      end

      it "redirects to the created fuel_type" do
        FuelType.stub(:new) { mock_fuel_type(:save => true) }
        post :create, :fuel_type => {}
        response.should redirect_to(fuel_type_url(mock_fuel_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fuel_type as @fuel_type" do
        FuelType.stub(:new).with({'these' => 'params'}) { mock_fuel_type(:save => false) }
        post :create, :fuel_type => {'these' => 'params'}
        assigns(:fuel_type).should be(mock_fuel_type)
      end

      it "re-renders the 'new' template" do
        FuelType.stub(:new) { mock_fuel_type(:save => false) }
        post :create, :fuel_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fuel_type" do
        FuelType.stub(:find).with("37") { mock_fuel_type }
        mock_fuel_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :fuel_type => {'these' => 'params'}
      end

      it "assigns the requested fuel_type as @fuel_type" do
        FuelType.stub(:find) { mock_fuel_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:fuel_type).should be(mock_fuel_type)
      end

      it "redirects to the fuel_type" do
        FuelType.stub(:find) { mock_fuel_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(fuel_type_url(mock_fuel_type))
      end
    end

    describe "with invalid params" do
      it "assigns the fuel_type as @fuel_type" do
        FuelType.stub(:find) { mock_fuel_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:fuel_type).should be(mock_fuel_type)
      end

      it "re-renders the 'edit' template" do
        FuelType.stub(:find) { mock_fuel_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fuel_type" do
      FuelType.stub(:find).with("37") { mock_fuel_type }
      mock_fuel_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the fuel_types list" do
      FuelType.stub(:find) { mock_fuel_type }
      delete :destroy, :id => "1"
      response.should redirect_to(fuel_types_url)
    end
  end

end
