require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe IlmoitusController do

  def mock_ilmoitu(stubs={})
    @mock_ilmoitu ||= mock_model(Ilmoitu, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ilmoitus as @ilmoitus" do
      Ilmoitu.stub(:all) { [mock_ilmoitu] }
      get :index
      assigns(:ilmoitus).should eq([mock_ilmoitu])
    end
  end

  describe "GET show" do
    it "assigns the requested ilmoitu as @ilmoitu" do
      Ilmoitu.stub(:find).with("37") { mock_ilmoitu }
      get :show, :id => "37"
      assigns(:ilmoitu).should be(mock_ilmoitu)
    end
  end

  describe "GET new" do
    it "assigns a new ilmoitu as @ilmoitu" do
      Ilmoitu.stub(:new) { mock_ilmoitu }
      get :new
      assigns(:ilmoitu).should be(mock_ilmoitu)
    end
  end

  describe "GET edit" do
    it "assigns the requested ilmoitu as @ilmoitu" do
      Ilmoitu.stub(:find).with("37") { mock_ilmoitu }
      get :edit, :id => "37"
      assigns(:ilmoitu).should be(mock_ilmoitu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ilmoitu as @ilmoitu" do
        Ilmoitu.stub(:new).with({'these' => 'params'}) { mock_ilmoitu(:save => true) }
        post :create, :ilmoitu => {'these' => 'params'}
        assigns(:ilmoitu).should be(mock_ilmoitu)
      end

      it "redirects to the created ilmoitu" do
        Ilmoitu.stub(:new) { mock_ilmoitu(:save => true) }
        post :create, :ilmoitu => {}
        response.should redirect_to(ilmoitu_url(mock_ilmoitu))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ilmoitu as @ilmoitu" do
        Ilmoitu.stub(:new).with({'these' => 'params'}) { mock_ilmoitu(:save => false) }
        post :create, :ilmoitu => {'these' => 'params'}
        assigns(:ilmoitu).should be(mock_ilmoitu)
      end

      it "re-renders the 'new' template" do
        Ilmoitu.stub(:new) { mock_ilmoitu(:save => false) }
        post :create, :ilmoitu => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ilmoitu" do
        Ilmoitu.stub(:find).with("37") { mock_ilmoitu }
        mock_ilmoitu.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ilmoitu => {'these' => 'params'}
      end

      it "assigns the requested ilmoitu as @ilmoitu" do
        Ilmoitu.stub(:find) { mock_ilmoitu(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ilmoitu).should be(mock_ilmoitu)
      end

      it "redirects to the ilmoitu" do
        Ilmoitu.stub(:find) { mock_ilmoitu(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ilmoitu_url(mock_ilmoitu))
      end
    end

    describe "with invalid params" do
      it "assigns the ilmoitu as @ilmoitu" do
        Ilmoitu.stub(:find) { mock_ilmoitu(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ilmoitu).should be(mock_ilmoitu)
      end

      it "re-renders the 'edit' template" do
        Ilmoitu.stub(:find) { mock_ilmoitu(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ilmoitu" do
      Ilmoitu.stub(:find).with("37") { mock_ilmoitu }
      mock_ilmoitu.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ilmoitus list" do
      Ilmoitu.stub(:find) { mock_ilmoitu }
      delete :destroy, :id => "1"
      response.should redirect_to(ilmoitus_url)
    end
  end

end
