require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineGrossWeightsController do

  def mock_machine_gross_weight(stubs={})
    @mock_machine_gross_weight ||= mock_model(MachineGrossWeight, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_gross_weights as @machine_gross_weights" do
      MachineGrossWeight.stub(:all) { [mock_machine_gross_weight] }
      get :index
      assigns(:machine_gross_weights).should eq([mock_machine_gross_weight])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_gross_weight as @machine_gross_weight" do
      MachineGrossWeight.stub(:find).with("37") { mock_machine_gross_weight }
      get :show, :id => "37"
      assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
    end
  end

  describe "GET new" do
    it "assigns a new machine_gross_weight as @machine_gross_weight" do
      MachineGrossWeight.stub(:new) { mock_machine_gross_weight }
      get :new
      assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_gross_weight as @machine_gross_weight" do
      MachineGrossWeight.stub(:find).with("37") { mock_machine_gross_weight }
      get :edit, :id => "37"
      assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_gross_weight as @machine_gross_weight" do
        MachineGrossWeight.stub(:new).with({'these' => 'params'}) { mock_machine_gross_weight(:save => true) }
        post :create, :machine_gross_weight => {'these' => 'params'}
        assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
      end

      it "redirects to the created machine_gross_weight" do
        MachineGrossWeight.stub(:new) { mock_machine_gross_weight(:save => true) }
        post :create, :machine_gross_weight => {}
        response.should redirect_to(machine_gross_weight_url(mock_machine_gross_weight))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_gross_weight as @machine_gross_weight" do
        MachineGrossWeight.stub(:new).with({'these' => 'params'}) { mock_machine_gross_weight(:save => false) }
        post :create, :machine_gross_weight => {'these' => 'params'}
        assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
      end

      it "re-renders the 'new' template" do
        MachineGrossWeight.stub(:new) { mock_machine_gross_weight(:save => false) }
        post :create, :machine_gross_weight => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_gross_weight" do
        MachineGrossWeight.stub(:find).with("37") { mock_machine_gross_weight }
        mock_machine_gross_weight.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_gross_weight => {'these' => 'params'}
      end

      it "assigns the requested machine_gross_weight as @machine_gross_weight" do
        MachineGrossWeight.stub(:find) { mock_machine_gross_weight(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
      end

      it "redirects to the machine_gross_weight" do
        MachineGrossWeight.stub(:find) { mock_machine_gross_weight(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_gross_weight_url(mock_machine_gross_weight))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_gross_weight as @machine_gross_weight" do
        MachineGrossWeight.stub(:find) { mock_machine_gross_weight(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_gross_weight).should be(mock_machine_gross_weight)
      end

      it "re-renders the 'edit' template" do
        MachineGrossWeight.stub(:find) { mock_machine_gross_weight(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_gross_weight" do
      MachineGrossWeight.stub(:find).with("37") { mock_machine_gross_weight }
      mock_machine_gross_weight.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_gross_weights list" do
      MachineGrossWeight.stub(:find) { mock_machine_gross_weight }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_gross_weights_url)
    end
  end

end
