require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachinePricesController do

  def mock_machine_price(stubs={})
    @mock_machine_price ||= mock_model(MachinePrice, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_prices as @machine_prices" do
      MachinePrice.stub(:all) { [mock_machine_price] }
      get :index
      assigns(:machine_prices).should eq([mock_machine_price])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_price as @machine_price" do
      MachinePrice.stub(:find).with("37") { mock_machine_price }
      get :show, :id => "37"
      assigns(:machine_price).should be(mock_machine_price)
    end
  end

  describe "GET new" do
    it "assigns a new machine_price as @machine_price" do
      MachinePrice.stub(:new) { mock_machine_price }
      get :new
      assigns(:machine_price).should be(mock_machine_price)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_price as @machine_price" do
      MachinePrice.stub(:find).with("37") { mock_machine_price }
      get :edit, :id => "37"
      assigns(:machine_price).should be(mock_machine_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_price as @machine_price" do
        MachinePrice.stub(:new).with({'these' => 'params'}) { mock_machine_price(:save => true) }
        post :create, :machine_price => {'these' => 'params'}
        assigns(:machine_price).should be(mock_machine_price)
      end

      it "redirects to the created machine_price" do
        MachinePrice.stub(:new) { mock_machine_price(:save => true) }
        post :create, :machine_price => {}
        response.should redirect_to(machine_price_url(mock_machine_price))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_price as @machine_price" do
        MachinePrice.stub(:new).with({'these' => 'params'}) { mock_machine_price(:save => false) }
        post :create, :machine_price => {'these' => 'params'}
        assigns(:machine_price).should be(mock_machine_price)
      end

      it "re-renders the 'new' template" do
        MachinePrice.stub(:new) { mock_machine_price(:save => false) }
        post :create, :machine_price => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_price" do
        MachinePrice.stub(:find).with("37") { mock_machine_price }
        mock_machine_price.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_price => {'these' => 'params'}
      end

      it "assigns the requested machine_price as @machine_price" do
        MachinePrice.stub(:find) { mock_machine_price(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_price).should be(mock_machine_price)
      end

      it "redirects to the machine_price" do
        MachinePrice.stub(:find) { mock_machine_price(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_price_url(mock_machine_price))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_price as @machine_price" do
        MachinePrice.stub(:find) { mock_machine_price(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_price).should be(mock_machine_price)
      end

      it "re-renders the 'edit' template" do
        MachinePrice.stub(:find) { mock_machine_price(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_price" do
      MachinePrice.stub(:find).with("37") { mock_machine_price }
      mock_machine_price.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_prices list" do
      MachinePrice.stub(:find) { mock_machine_price }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_prices_url)
    end
  end

end
