require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineUserPhonesController do

  def mock_machine_user_phone(stubs={})
    @mock_machine_user_phone ||= mock_model(MachineUserPhone, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_user_phones as @machine_user_phones" do
      MachineUserPhone.stub(:all) { [mock_machine_user_phone] }
      get :index
      assigns(:machine_user_phones).should eq([mock_machine_user_phone])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_user_phone as @machine_user_phone" do
      MachineUserPhone.stub(:find).with("37") { mock_machine_user_phone }
      get :show, :id => "37"
      assigns(:machine_user_phone).should be(mock_machine_user_phone)
    end
  end

  describe "GET new" do
    it "assigns a new machine_user_phone as @machine_user_phone" do
      MachineUserPhone.stub(:new) { mock_machine_user_phone }
      get :new
      assigns(:machine_user_phone).should be(mock_machine_user_phone)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_user_phone as @machine_user_phone" do
      MachineUserPhone.stub(:find).with("37") { mock_machine_user_phone }
      get :edit, :id => "37"
      assigns(:machine_user_phone).should be(mock_machine_user_phone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_user_phone as @machine_user_phone" do
        MachineUserPhone.stub(:new).with({'these' => 'params'}) { mock_machine_user_phone(:save => true) }
        post :create, :machine_user_phone => {'these' => 'params'}
        assigns(:machine_user_phone).should be(mock_machine_user_phone)
      end

      it "redirects to the created machine_user_phone" do
        MachineUserPhone.stub(:new) { mock_machine_user_phone(:save => true) }
        post :create, :machine_user_phone => {}
        response.should redirect_to(machine_user_phone_url(mock_machine_user_phone))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_user_phone as @machine_user_phone" do
        MachineUserPhone.stub(:new).with({'these' => 'params'}) { mock_machine_user_phone(:save => false) }
        post :create, :machine_user_phone => {'these' => 'params'}
        assigns(:machine_user_phone).should be(mock_machine_user_phone)
      end

      it "re-renders the 'new' template" do
        MachineUserPhone.stub(:new) { mock_machine_user_phone(:save => false) }
        post :create, :machine_user_phone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_user_phone" do
        MachineUserPhone.stub(:find).with("37") { mock_machine_user_phone }
        mock_machine_user_phone.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_user_phone => {'these' => 'params'}
      end

      it "assigns the requested machine_user_phone as @machine_user_phone" do
        MachineUserPhone.stub(:find) { mock_machine_user_phone(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_user_phone).should be(mock_machine_user_phone)
      end

      it "redirects to the machine_user_phone" do
        MachineUserPhone.stub(:find) { mock_machine_user_phone(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_user_phone_url(mock_machine_user_phone))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_user_phone as @machine_user_phone" do
        MachineUserPhone.stub(:find) { mock_machine_user_phone(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_user_phone).should be(mock_machine_user_phone)
      end

      it "re-renders the 'edit' template" do
        MachineUserPhone.stub(:find) { mock_machine_user_phone(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_user_phone" do
      MachineUserPhone.stub(:find).with("37") { mock_machine_user_phone }
      mock_machine_user_phone.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_user_phones list" do
      MachineUserPhone.stub(:find) { mock_machine_user_phone }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_user_phones_url)
    end
  end

end
