require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineUserNamesController do

  def mock_machine_user_name(stubs={})
    @mock_machine_user_name ||= mock_model(MachineUserName, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_user_names as @machine_user_names" do
      MachineUserName.stub(:all) { [mock_machine_user_name] }
      get :index
      assigns(:machine_user_names).should eq([mock_machine_user_name])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_user_name as @machine_user_name" do
      MachineUserName.stub(:find).with("37") { mock_machine_user_name }
      get :show, :id => "37"
      assigns(:machine_user_name).should be(mock_machine_user_name)
    end
  end

  describe "GET new" do
    it "assigns a new machine_user_name as @machine_user_name" do
      MachineUserName.stub(:new) { mock_machine_user_name }
      get :new
      assigns(:machine_user_name).should be(mock_machine_user_name)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_user_name as @machine_user_name" do
      MachineUserName.stub(:find).with("37") { mock_machine_user_name }
      get :edit, :id => "37"
      assigns(:machine_user_name).should be(mock_machine_user_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_user_name as @machine_user_name" do
        MachineUserName.stub(:new).with({'these' => 'params'}) { mock_machine_user_name(:save => true) }
        post :create, :machine_user_name => {'these' => 'params'}
        assigns(:machine_user_name).should be(mock_machine_user_name)
      end

      it "redirects to the created machine_user_name" do
        MachineUserName.stub(:new) { mock_machine_user_name(:save => true) }
        post :create, :machine_user_name => {}
        response.should redirect_to(machine_user_name_url(mock_machine_user_name))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_user_name as @machine_user_name" do
        MachineUserName.stub(:new).with({'these' => 'params'}) { mock_machine_user_name(:save => false) }
        post :create, :machine_user_name => {'these' => 'params'}
        assigns(:machine_user_name).should be(mock_machine_user_name)
      end

      it "re-renders the 'new' template" do
        MachineUserName.stub(:new) { mock_machine_user_name(:save => false) }
        post :create, :machine_user_name => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_user_name" do
        MachineUserName.stub(:find).with("37") { mock_machine_user_name }
        mock_machine_user_name.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_user_name => {'these' => 'params'}
      end

      it "assigns the requested machine_user_name as @machine_user_name" do
        MachineUserName.stub(:find) { mock_machine_user_name(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_user_name).should be(mock_machine_user_name)
      end

      it "redirects to the machine_user_name" do
        MachineUserName.stub(:find) { mock_machine_user_name(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_user_name_url(mock_machine_user_name))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_user_name as @machine_user_name" do
        MachineUserName.stub(:find) { mock_machine_user_name(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_user_name).should be(mock_machine_user_name)
      end

      it "re-renders the 'edit' template" do
        MachineUserName.stub(:find) { mock_machine_user_name(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_user_name" do
      MachineUserName.stub(:find).with("37") { mock_machine_user_name }
      mock_machine_user_name.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_user_names list" do
      MachineUserName.stub(:find) { mock_machine_user_name }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_user_names_url)
    end
  end

end
