require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineFuelTypesController do

  def mock_machine_fuel_type(stubs={})
    @mock_machine_fuel_type ||= mock_model(MachineFuelType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_fuel_types as @machine_fuel_types" do
      MachineFuelType.stub(:all) { [mock_machine_fuel_type] }
      get :index
      assigns(:machine_fuel_types).should eq([mock_machine_fuel_type])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_fuel_type as @machine_fuel_type" do
      MachineFuelType.stub(:find).with("37") { mock_machine_fuel_type }
      get :show, :id => "37"
      assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
    end
  end

  describe "GET new" do
    it "assigns a new machine_fuel_type as @machine_fuel_type" do
      MachineFuelType.stub(:new) { mock_machine_fuel_type }
      get :new
      assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_fuel_type as @machine_fuel_type" do
      MachineFuelType.stub(:find).with("37") { mock_machine_fuel_type }
      get :edit, :id => "37"
      assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_fuel_type as @machine_fuel_type" do
        MachineFuelType.stub(:new).with({'these' => 'params'}) { mock_machine_fuel_type(:save => true) }
        post :create, :machine_fuel_type => {'these' => 'params'}
        assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
      end

      it "redirects to the created machine_fuel_type" do
        MachineFuelType.stub(:new) { mock_machine_fuel_type(:save => true) }
        post :create, :machine_fuel_type => {}
        response.should redirect_to(machine_fuel_type_url(mock_machine_fuel_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_fuel_type as @machine_fuel_type" do
        MachineFuelType.stub(:new).with({'these' => 'params'}) { mock_machine_fuel_type(:save => false) }
        post :create, :machine_fuel_type => {'these' => 'params'}
        assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
      end

      it "re-renders the 'new' template" do
        MachineFuelType.stub(:new) { mock_machine_fuel_type(:save => false) }
        post :create, :machine_fuel_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_fuel_type" do
        MachineFuelType.stub(:find).with("37") { mock_machine_fuel_type }
        mock_machine_fuel_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_fuel_type => {'these' => 'params'}
      end

      it "assigns the requested machine_fuel_type as @machine_fuel_type" do
        MachineFuelType.stub(:find) { mock_machine_fuel_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
      end

      it "redirects to the machine_fuel_type" do
        MachineFuelType.stub(:find) { mock_machine_fuel_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_fuel_type_url(mock_machine_fuel_type))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_fuel_type as @machine_fuel_type" do
        MachineFuelType.stub(:find) { mock_machine_fuel_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_fuel_type).should be(mock_machine_fuel_type)
      end

      it "re-renders the 'edit' template" do
        MachineFuelType.stub(:find) { mock_machine_fuel_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_fuel_type" do
      MachineFuelType.stub(:find).with("37") { mock_machine_fuel_type }
      mock_machine_fuel_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_fuel_types list" do
      MachineFuelType.stub(:find) { mock_machine_fuel_type }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_fuel_types_url)
    end
  end

end
