require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineColorsController do

  def mock_machine_color(stubs={})
    @mock_machine_color ||= mock_model(MachineColor, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_colors as @machine_colors" do
      MachineColor.stub(:all) { [mock_machine_color] }
      get :index
      assigns(:machine_colors).should eq([mock_machine_color])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_color as @machine_color" do
      MachineColor.stub(:find).with("37") { mock_machine_color }
      get :show, :id => "37"
      assigns(:machine_color).should be(mock_machine_color)
    end
  end

  describe "GET new" do
    it "assigns a new machine_color as @machine_color" do
      MachineColor.stub(:new) { mock_machine_color }
      get :new
      assigns(:machine_color).should be(mock_machine_color)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_color as @machine_color" do
      MachineColor.stub(:find).with("37") { mock_machine_color }
      get :edit, :id => "37"
      assigns(:machine_color).should be(mock_machine_color)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_color as @machine_color" do
        MachineColor.stub(:new).with({'these' => 'params'}) { mock_machine_color(:save => true) }
        post :create, :machine_color => {'these' => 'params'}
        assigns(:machine_color).should be(mock_machine_color)
      end

      it "redirects to the created machine_color" do
        MachineColor.stub(:new) { mock_machine_color(:save => true) }
        post :create, :machine_color => {}
        response.should redirect_to(machine_color_url(mock_machine_color))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_color as @machine_color" do
        MachineColor.stub(:new).with({'these' => 'params'}) { mock_machine_color(:save => false) }
        post :create, :machine_color => {'these' => 'params'}
        assigns(:machine_color).should be(mock_machine_color)
      end

      it "re-renders the 'new' template" do
        MachineColor.stub(:new) { mock_machine_color(:save => false) }
        post :create, :machine_color => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_color" do
        MachineColor.stub(:find).with("37") { mock_machine_color }
        mock_machine_color.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_color => {'these' => 'params'}
      end

      it "assigns the requested machine_color as @machine_color" do
        MachineColor.stub(:find) { mock_machine_color(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_color).should be(mock_machine_color)
      end

      it "redirects to the machine_color" do
        MachineColor.stub(:find) { mock_machine_color(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_color_url(mock_machine_color))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_color as @machine_color" do
        MachineColor.stub(:find) { mock_machine_color(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_color).should be(mock_machine_color)
      end

      it "re-renders the 'edit' template" do
        MachineColor.stub(:find) { mock_machine_color(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_color" do
      MachineColor.stub(:find).with("37") { mock_machine_color }
      mock_machine_color.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_colors list" do
      MachineColor.stub(:find) { mock_machine_color }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_colors_url)
    end
  end

end
