require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineUserEmailsController do

  def mock_machine_user_email(stubs={})
    @mock_machine_user_email ||= mock_model(MachineUserEmail, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_user_emails as @machine_user_emails" do
      MachineUserEmail.stub(:all) { [mock_machine_user_email] }
      get :index
      assigns(:machine_user_emails).should eq([mock_machine_user_email])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_user_email as @machine_user_email" do
      MachineUserEmail.stub(:find).with("37") { mock_machine_user_email }
      get :show, :id => "37"
      assigns(:machine_user_email).should be(mock_machine_user_email)
    end
  end

  describe "GET new" do
    it "assigns a new machine_user_email as @machine_user_email" do
      MachineUserEmail.stub(:new) { mock_machine_user_email }
      get :new
      assigns(:machine_user_email).should be(mock_machine_user_email)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_user_email as @machine_user_email" do
      MachineUserEmail.stub(:find).with("37") { mock_machine_user_email }
      get :edit, :id => "37"
      assigns(:machine_user_email).should be(mock_machine_user_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_user_email as @machine_user_email" do
        MachineUserEmail.stub(:new).with({'these' => 'params'}) { mock_machine_user_email(:save => true) }
        post :create, :machine_user_email => {'these' => 'params'}
        assigns(:machine_user_email).should be(mock_machine_user_email)
      end

      it "redirects to the created machine_user_email" do
        MachineUserEmail.stub(:new) { mock_machine_user_email(:save => true) }
        post :create, :machine_user_email => {}
        response.should redirect_to(machine_user_email_url(mock_machine_user_email))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_user_email as @machine_user_email" do
        MachineUserEmail.stub(:new).with({'these' => 'params'}) { mock_machine_user_email(:save => false) }
        post :create, :machine_user_email => {'these' => 'params'}
        assigns(:machine_user_email).should be(mock_machine_user_email)
      end

      it "re-renders the 'new' template" do
        MachineUserEmail.stub(:new) { mock_machine_user_email(:save => false) }
        post :create, :machine_user_email => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_user_email" do
        MachineUserEmail.stub(:find).with("37") { mock_machine_user_email }
        mock_machine_user_email.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_user_email => {'these' => 'params'}
      end

      it "assigns the requested machine_user_email as @machine_user_email" do
        MachineUserEmail.stub(:find) { mock_machine_user_email(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_user_email).should be(mock_machine_user_email)
      end

      it "redirects to the machine_user_email" do
        MachineUserEmail.stub(:find) { mock_machine_user_email(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_user_email_url(mock_machine_user_email))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_user_email as @machine_user_email" do
        MachineUserEmail.stub(:find) { mock_machine_user_email(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_user_email).should be(mock_machine_user_email)
      end

      it "re-renders the 'edit' template" do
        MachineUserEmail.stub(:find) { mock_machine_user_email(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_user_email" do
      MachineUserEmail.stub(:find).with("37") { mock_machine_user_email }
      mock_machine_user_email.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_user_emails list" do
      MachineUserEmail.stub(:find) { mock_machine_user_email }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_user_emails_url)
    end
  end

end
