require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MachineTotalOwnersController do

  def mock_machine_total_owner(stubs={})
    @mock_machine_total_owner ||= mock_model(MachineTotalOwner, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all machine_total_owners as @machine_total_owners" do
      MachineTotalOwner.stub(:all) { [mock_machine_total_owner] }
      get :index
      assigns(:machine_total_owners).should eq([mock_machine_total_owner])
    end
  end

  describe "GET show" do
    it "assigns the requested machine_total_owner as @machine_total_owner" do
      MachineTotalOwner.stub(:find).with("37") { mock_machine_total_owner }
      get :show, :id => "37"
      assigns(:machine_total_owner).should be(mock_machine_total_owner)
    end
  end

  describe "GET new" do
    it "assigns a new machine_total_owner as @machine_total_owner" do
      MachineTotalOwner.stub(:new) { mock_machine_total_owner }
      get :new
      assigns(:machine_total_owner).should be(mock_machine_total_owner)
    end
  end

  describe "GET edit" do
    it "assigns the requested machine_total_owner as @machine_total_owner" do
      MachineTotalOwner.stub(:find).with("37") { mock_machine_total_owner }
      get :edit, :id => "37"
      assigns(:machine_total_owner).should be(mock_machine_total_owner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created machine_total_owner as @machine_total_owner" do
        MachineTotalOwner.stub(:new).with({'these' => 'params'}) { mock_machine_total_owner(:save => true) }
        post :create, :machine_total_owner => {'these' => 'params'}
        assigns(:machine_total_owner).should be(mock_machine_total_owner)
      end

      it "redirects to the created machine_total_owner" do
        MachineTotalOwner.stub(:new) { mock_machine_total_owner(:save => true) }
        post :create, :machine_total_owner => {}
        response.should redirect_to(machine_total_owner_url(mock_machine_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved machine_total_owner as @machine_total_owner" do
        MachineTotalOwner.stub(:new).with({'these' => 'params'}) { mock_machine_total_owner(:save => false) }
        post :create, :machine_total_owner => {'these' => 'params'}
        assigns(:machine_total_owner).should be(mock_machine_total_owner)
      end

      it "re-renders the 'new' template" do
        MachineTotalOwner.stub(:new) { mock_machine_total_owner(:save => false) }
        post :create, :machine_total_owner => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested machine_total_owner" do
        MachineTotalOwner.stub(:find).with("37") { mock_machine_total_owner }
        mock_machine_total_owner.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :machine_total_owner => {'these' => 'params'}
      end

      it "assigns the requested machine_total_owner as @machine_total_owner" do
        MachineTotalOwner.stub(:find) { mock_machine_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:machine_total_owner).should be(mock_machine_total_owner)
      end

      it "redirects to the machine_total_owner" do
        MachineTotalOwner.stub(:find) { mock_machine_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(machine_total_owner_url(mock_machine_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns the machine_total_owner as @machine_total_owner" do
        MachineTotalOwner.stub(:find) { mock_machine_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:machine_total_owner).should be(mock_machine_total_owner)
      end

      it "re-renders the 'edit' template" do
        MachineTotalOwner.stub(:find) { mock_machine_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested machine_total_owner" do
      MachineTotalOwner.stub(:find).with("37") { mock_machine_total_owner }
      mock_machine_total_owner.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the machine_total_owners list" do
      MachineTotalOwner.stub(:find) { mock_machine_total_owner }
      delete :destroy, :id => "1"
      response.should redirect_to(machine_total_owners_url)
    end
  end

end
