require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MakeSectionsController do

  def mock_make_section(stubs={})
    @mock_make_section ||= mock_model(MakeSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all make_sections as @make_sections" do
      MakeSection.stub(:all) { [mock_make_section] }
      get :index
      assigns(:make_sections).should eq([mock_make_section])
    end
  end

  describe "GET show" do
    it "assigns the requested make_section as @make_section" do
      MakeSection.stub(:find).with("37") { mock_make_section }
      get :show, :id => "37"
      assigns(:make_section).should be(mock_make_section)
    end
  end

  describe "GET new" do
    it "assigns a new make_section as @make_section" do
      MakeSection.stub(:new) { mock_make_section }
      get :new
      assigns(:make_section).should be(mock_make_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested make_section as @make_section" do
      MakeSection.stub(:find).with("37") { mock_make_section }
      get :edit, :id => "37"
      assigns(:make_section).should be(mock_make_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created make_section as @make_section" do
        MakeSection.stub(:new).with({'these' => 'params'}) { mock_make_section(:save => true) }
        post :create, :make_section => {'these' => 'params'}
        assigns(:make_section).should be(mock_make_section)
      end

      it "redirects to the created make_section" do
        MakeSection.stub(:new) { mock_make_section(:save => true) }
        post :create, :make_section => {}
        response.should redirect_to(make_section_url(mock_make_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved make_section as @make_section" do
        MakeSection.stub(:new).with({'these' => 'params'}) { mock_make_section(:save => false) }
        post :create, :make_section => {'these' => 'params'}
        assigns(:make_section).should be(mock_make_section)
      end

      it "re-renders the 'new' template" do
        MakeSection.stub(:new) { mock_make_section(:save => false) }
        post :create, :make_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested make_section" do
        MakeSection.stub(:find).with("37") { mock_make_section }
        mock_make_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :make_section => {'these' => 'params'}
      end

      it "assigns the requested make_section as @make_section" do
        MakeSection.stub(:find) { mock_make_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:make_section).should be(mock_make_section)
      end

      it "redirects to the make_section" do
        MakeSection.stub(:find) { mock_make_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(make_section_url(mock_make_section))
      end
    end

    describe "with invalid params" do
      it "assigns the make_section as @make_section" do
        MakeSection.stub(:find) { mock_make_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:make_section).should be(mock_make_section)
      end

      it "re-renders the 'edit' template" do
        MakeSection.stub(:find) { mock_make_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested make_section" do
      MakeSection.stub(:find).with("37") { mock_make_section }
      mock_make_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the make_sections list" do
      MakeSection.stub(:find) { mock_make_section }
      delete :destroy, :id => "1"
      response.should redirect_to(make_sections_url)
    end
  end

end
