require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ModelSectionsController do

  def mock_model_section(stubs={})
    @mock_model_section ||= mock_model(ModelSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all model_sections as @model_sections" do
      ModelSection.stub(:all) { [mock_model_section] }
      get :index
      assigns(:model_sections).should eq([mock_model_section])
    end
  end

  describe "GET show" do
    it "assigns the requested model_section as @model_section" do
      ModelSection.stub(:find).with("37") { mock_model_section }
      get :show, :id => "37"
      assigns(:model_section).should be(mock_model_section)
    end
  end

  describe "GET new" do
    it "assigns a new model_section as @model_section" do
      ModelSection.stub(:new) { mock_model_section }
      get :new
      assigns(:model_section).should be(mock_model_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested model_section as @model_section" do
      ModelSection.stub(:find).with("37") { mock_model_section }
      get :edit, :id => "37"
      assigns(:model_section).should be(mock_model_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created model_section as @model_section" do
        ModelSection.stub(:new).with({'these' => 'params'}) { mock_model_section(:save => true) }
        post :create, :model_section => {'these' => 'params'}
        assigns(:model_section).should be(mock_model_section)
      end

      it "redirects to the created model_section" do
        ModelSection.stub(:new) { mock_model_section(:save => true) }
        post :create, :model_section => {}
        response.should redirect_to(model_section_url(mock_model_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved model_section as @model_section" do
        ModelSection.stub(:new).with({'these' => 'params'}) { mock_model_section(:save => false) }
        post :create, :model_section => {'these' => 'params'}
        assigns(:model_section).should be(mock_model_section)
      end

      it "re-renders the 'new' template" do
        ModelSection.stub(:new) { mock_model_section(:save => false) }
        post :create, :model_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested model_section" do
        ModelSection.stub(:find).with("37") { mock_model_section }
        mock_model_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :model_section => {'these' => 'params'}
      end

      it "assigns the requested model_section as @model_section" do
        ModelSection.stub(:find) { mock_model_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:model_section).should be(mock_model_section)
      end

      it "redirects to the model_section" do
        ModelSection.stub(:find) { mock_model_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(model_section_url(mock_model_section))
      end
    end

    describe "with invalid params" do
      it "assigns the model_section as @model_section" do
        ModelSection.stub(:find) { mock_model_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:model_section).should be(mock_model_section)
      end

      it "re-renders the 'edit' template" do
        ModelSection.stub(:find) { mock_model_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested model_section" do
      ModelSection.stub(:find).with("37") { mock_model_section }
      mock_model_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the model_sections list" do
      ModelSection.stub(:find) { mock_model_section }
      delete :destroy, :id => "1"
      response.should redirect_to(model_sections_url)
    end
  end

end
