require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoUserEmailsController do

  def mock_moto_user_email(stubs={})
    @mock_moto_user_email ||= mock_model(MotoUserEmail, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_user_emails as @moto_user_emails" do
      MotoUserEmail.stub(:all) { [mock_moto_user_email] }
      get :index
      assigns(:moto_user_emails).should eq([mock_moto_user_email])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_user_email as @moto_user_email" do
      MotoUserEmail.stub(:find).with("37") { mock_moto_user_email }
      get :show, :id => "37"
      assigns(:moto_user_email).should be(mock_moto_user_email)
    end
  end

  describe "GET new" do
    it "assigns a new moto_user_email as @moto_user_email" do
      MotoUserEmail.stub(:new) { mock_moto_user_email }
      get :new
      assigns(:moto_user_email).should be(mock_moto_user_email)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_user_email as @moto_user_email" do
      MotoUserEmail.stub(:find).with("37") { mock_moto_user_email }
      get :edit, :id => "37"
      assigns(:moto_user_email).should be(mock_moto_user_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_user_email as @moto_user_email" do
        MotoUserEmail.stub(:new).with({'these' => 'params'}) { mock_moto_user_email(:save => true) }
        post :create, :moto_user_email => {'these' => 'params'}
        assigns(:moto_user_email).should be(mock_moto_user_email)
      end

      it "redirects to the created moto_user_email" do
        MotoUserEmail.stub(:new) { mock_moto_user_email(:save => true) }
        post :create, :moto_user_email => {}
        response.should redirect_to(moto_user_email_url(mock_moto_user_email))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_user_email as @moto_user_email" do
        MotoUserEmail.stub(:new).with({'these' => 'params'}) { mock_moto_user_email(:save => false) }
        post :create, :moto_user_email => {'these' => 'params'}
        assigns(:moto_user_email).should be(mock_moto_user_email)
      end

      it "re-renders the 'new' template" do
        MotoUserEmail.stub(:new) { mock_moto_user_email(:save => false) }
        post :create, :moto_user_email => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_user_email" do
        MotoUserEmail.stub(:find).with("37") { mock_moto_user_email }
        mock_moto_user_email.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_user_email => {'these' => 'params'}
      end

      it "assigns the requested moto_user_email as @moto_user_email" do
        MotoUserEmail.stub(:find) { mock_moto_user_email(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_user_email).should be(mock_moto_user_email)
      end

      it "redirects to the moto_user_email" do
        MotoUserEmail.stub(:find) { mock_moto_user_email(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_user_email_url(mock_moto_user_email))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_user_email as @moto_user_email" do
        MotoUserEmail.stub(:find) { mock_moto_user_email(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_user_email).should be(mock_moto_user_email)
      end

      it "re-renders the 'edit' template" do
        MotoUserEmail.stub(:find) { mock_moto_user_email(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_user_email" do
      MotoUserEmail.stub(:find).with("37") { mock_moto_user_email }
      mock_moto_user_email.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_user_emails list" do
      MotoUserEmail.stub(:find) { mock_moto_user_email }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_user_emails_url)
    end
  end

end
