require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoMileagesController do

  def mock_moto_mileage(stubs={})
    @mock_moto_mileage ||= mock_model(MotoMileage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_mileages as @moto_mileages" do
      MotoMileage.stub(:all) { [mock_moto_mileage] }
      get :index
      assigns(:moto_mileages).should eq([mock_moto_mileage])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_mileage as @moto_mileage" do
      MotoMileage.stub(:find).with("37") { mock_moto_mileage }
      get :show, :id => "37"
      assigns(:moto_mileage).should be(mock_moto_mileage)
    end
  end

  describe "GET new" do
    it "assigns a new moto_mileage as @moto_mileage" do
      MotoMileage.stub(:new) { mock_moto_mileage }
      get :new
      assigns(:moto_mileage).should be(mock_moto_mileage)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_mileage as @moto_mileage" do
      MotoMileage.stub(:find).with("37") { mock_moto_mileage }
      get :edit, :id => "37"
      assigns(:moto_mileage).should be(mock_moto_mileage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_mileage as @moto_mileage" do
        MotoMileage.stub(:new).with({'these' => 'params'}) { mock_moto_mileage(:save => true) }
        post :create, :moto_mileage => {'these' => 'params'}
        assigns(:moto_mileage).should be(mock_moto_mileage)
      end

      it "redirects to the created moto_mileage" do
        MotoMileage.stub(:new) { mock_moto_mileage(:save => true) }
        post :create, :moto_mileage => {}
        response.should redirect_to(moto_mileage_url(mock_moto_mileage))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_mileage as @moto_mileage" do
        MotoMileage.stub(:new).with({'these' => 'params'}) { mock_moto_mileage(:save => false) }
        post :create, :moto_mileage => {'these' => 'params'}
        assigns(:moto_mileage).should be(mock_moto_mileage)
      end

      it "re-renders the 'new' template" do
        MotoMileage.stub(:new) { mock_moto_mileage(:save => false) }
        post :create, :moto_mileage => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_mileage" do
        MotoMileage.stub(:find).with("37") { mock_moto_mileage }
        mock_moto_mileage.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_mileage => {'these' => 'params'}
      end

      it "assigns the requested moto_mileage as @moto_mileage" do
        MotoMileage.stub(:find) { mock_moto_mileage(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_mileage).should be(mock_moto_mileage)
      end

      it "redirects to the moto_mileage" do
        MotoMileage.stub(:find) { mock_moto_mileage(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_mileage_url(mock_moto_mileage))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_mileage as @moto_mileage" do
        MotoMileage.stub(:find) { mock_moto_mileage(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_mileage).should be(mock_moto_mileage)
      end

      it "re-renders the 'edit' template" do
        MotoMileage.stub(:find) { mock_moto_mileage(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_mileage" do
      MotoMileage.stub(:find).with("37") { mock_moto_mileage }
      mock_moto_mileage.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_mileages list" do
      MotoMileage.stub(:find) { mock_moto_mileage }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_mileages_url)
    end
  end

end
