require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoColorsController do

  def mock_moto_color(stubs={})
    @mock_moto_color ||= mock_model(MotoColor, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_colors as @moto_colors" do
      MotoColor.stub(:all) { [mock_moto_color] }
      get :index
      assigns(:moto_colors).should eq([mock_moto_color])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_color as @moto_color" do
      MotoColor.stub(:find).with("37") { mock_moto_color }
      get :show, :id => "37"
      assigns(:moto_color).should be(mock_moto_color)
    end
  end

  describe "GET new" do
    it "assigns a new moto_color as @moto_color" do
      MotoColor.stub(:new) { mock_moto_color }
      get :new
      assigns(:moto_color).should be(mock_moto_color)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_color as @moto_color" do
      MotoColor.stub(:find).with("37") { mock_moto_color }
      get :edit, :id => "37"
      assigns(:moto_color).should be(mock_moto_color)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_color as @moto_color" do
        MotoColor.stub(:new).with({'these' => 'params'}) { mock_moto_color(:save => true) }
        post :create, :moto_color => {'these' => 'params'}
        assigns(:moto_color).should be(mock_moto_color)
      end

      it "redirects to the created moto_color" do
        MotoColor.stub(:new) { mock_moto_color(:save => true) }
        post :create, :moto_color => {}
        response.should redirect_to(moto_color_url(mock_moto_color))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_color as @moto_color" do
        MotoColor.stub(:new).with({'these' => 'params'}) { mock_moto_color(:save => false) }
        post :create, :moto_color => {'these' => 'params'}
        assigns(:moto_color).should be(mock_moto_color)
      end

      it "re-renders the 'new' template" do
        MotoColor.stub(:new) { mock_moto_color(:save => false) }
        post :create, :moto_color => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_color" do
        MotoColor.stub(:find).with("37") { mock_moto_color }
        mock_moto_color.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_color => {'these' => 'params'}
      end

      it "assigns the requested moto_color as @moto_color" do
        MotoColor.stub(:find) { mock_moto_color(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_color).should be(mock_moto_color)
      end

      it "redirects to the moto_color" do
        MotoColor.stub(:find) { mock_moto_color(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_color_url(mock_moto_color))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_color as @moto_color" do
        MotoColor.stub(:find) { mock_moto_color(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_color).should be(mock_moto_color)
      end

      it "re-renders the 'edit' template" do
        MotoColor.stub(:find) { mock_moto_color(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_color" do
      MotoColor.stub(:find).with("37") { mock_moto_color }
      mock_moto_color.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_colors list" do
      MotoColor.stub(:find) { mock_moto_color }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_colors_url)
    end
  end

end
