require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoInformationsController do

  def mock_moto_information(stubs={})
    @mock_moto_information ||= mock_model(MotoInformation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_informations as @moto_informations" do
      MotoInformation.stub(:all) { [mock_moto_information] }
      get :index
      assigns(:moto_informations).should eq([mock_moto_information])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_information as @moto_information" do
      MotoInformation.stub(:find).with("37") { mock_moto_information }
      get :show, :id => "37"
      assigns(:moto_information).should be(mock_moto_information)
    end
  end

  describe "GET new" do
    it "assigns a new moto_information as @moto_information" do
      MotoInformation.stub(:new) { mock_moto_information }
      get :new
      assigns(:moto_information).should be(mock_moto_information)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_information as @moto_information" do
      MotoInformation.stub(:find).with("37") { mock_moto_information }
      get :edit, :id => "37"
      assigns(:moto_information).should be(mock_moto_information)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_information as @moto_information" do
        MotoInformation.stub(:new).with({'these' => 'params'}) { mock_moto_information(:save => true) }
        post :create, :moto_information => {'these' => 'params'}
        assigns(:moto_information).should be(mock_moto_information)
      end

      it "redirects to the created moto_information" do
        MotoInformation.stub(:new) { mock_moto_information(:save => true) }
        post :create, :moto_information => {}
        response.should redirect_to(moto_information_url(mock_moto_information))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_information as @moto_information" do
        MotoInformation.stub(:new).with({'these' => 'params'}) { mock_moto_information(:save => false) }
        post :create, :moto_information => {'these' => 'params'}
        assigns(:moto_information).should be(mock_moto_information)
      end

      it "re-renders the 'new' template" do
        MotoInformation.stub(:new) { mock_moto_information(:save => false) }
        post :create, :moto_information => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_information" do
        MotoInformation.stub(:find).with("37") { mock_moto_information }
        mock_moto_information.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_information => {'these' => 'params'}
      end

      it "assigns the requested moto_information as @moto_information" do
        MotoInformation.stub(:find) { mock_moto_information(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_information).should be(mock_moto_information)
      end

      it "redirects to the moto_information" do
        MotoInformation.stub(:find) { mock_moto_information(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_information_url(mock_moto_information))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_information as @moto_information" do
        MotoInformation.stub(:find) { mock_moto_information(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_information).should be(mock_moto_information)
      end

      it "re-renders the 'edit' template" do
        MotoInformation.stub(:find) { mock_moto_information(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_information" do
      MotoInformation.stub(:find).with("37") { mock_moto_information }
      mock_moto_information.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_informations list" do
      MotoInformation.stub(:find) { mock_moto_information }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_informations_url)
    end
  end

end
