require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoPostsController do

  def mock_moto_post(stubs={})
    @mock_moto_post ||= mock_model(MotoPost, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_posts as @moto_posts" do
      MotoPost.stub(:all) { [mock_moto_post] }
      get :index
      assigns(:moto_posts).should eq([mock_moto_post])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_post as @moto_post" do
      MotoPost.stub(:find).with("37") { mock_moto_post }
      get :show, :id => "37"
      assigns(:moto_post).should be(mock_moto_post)
    end
  end

  describe "GET new" do
    it "assigns a new moto_post as @moto_post" do
      MotoPost.stub(:new) { mock_moto_post }
      get :new
      assigns(:moto_post).should be(mock_moto_post)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_post as @moto_post" do
      MotoPost.stub(:find).with("37") { mock_moto_post }
      get :edit, :id => "37"
      assigns(:moto_post).should be(mock_moto_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_post as @moto_post" do
        MotoPost.stub(:new).with({'these' => 'params'}) { mock_moto_post(:save => true) }
        post :create, :moto_post => {'these' => 'params'}
        assigns(:moto_post).should be(mock_moto_post)
      end

      it "redirects to the created moto_post" do
        MotoPost.stub(:new) { mock_moto_post(:save => true) }
        post :create, :moto_post => {}
        response.should redirect_to(moto_post_url(mock_moto_post))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_post as @moto_post" do
        MotoPost.stub(:new).with({'these' => 'params'}) { mock_moto_post(:save => false) }
        post :create, :moto_post => {'these' => 'params'}
        assigns(:moto_post).should be(mock_moto_post)
      end

      it "re-renders the 'new' template" do
        MotoPost.stub(:new) { mock_moto_post(:save => false) }
        post :create, :moto_post => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_post" do
        MotoPost.stub(:find).with("37") { mock_moto_post }
        mock_moto_post.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_post => {'these' => 'params'}
      end

      it "assigns the requested moto_post as @moto_post" do
        MotoPost.stub(:find) { mock_moto_post(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_post).should be(mock_moto_post)
      end

      it "redirects to the moto_post" do
        MotoPost.stub(:find) { mock_moto_post(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_post_url(mock_moto_post))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_post as @moto_post" do
        MotoPost.stub(:find) { mock_moto_post(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_post).should be(mock_moto_post)
      end

      it "re-renders the 'edit' template" do
        MotoPost.stub(:find) { mock_moto_post(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_post" do
      MotoPost.stub(:find).with("37") { mock_moto_post }
      mock_moto_post.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_posts list" do
      MotoPost.stub(:find) { mock_moto_post }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_posts_url)
    end
  end

end
