require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoEngineSizesController do

  def mock_moto_engine_size(stubs={})
    @mock_moto_engine_size ||= mock_model(MotoEngineSize, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_engine_sizes as @moto_engine_sizes" do
      MotoEngineSize.stub(:all) { [mock_moto_engine_size] }
      get :index
      assigns(:moto_engine_sizes).should eq([mock_moto_engine_size])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_engine_size as @moto_engine_size" do
      MotoEngineSize.stub(:find).with("37") { mock_moto_engine_size }
      get :show, :id => "37"
      assigns(:moto_engine_size).should be(mock_moto_engine_size)
    end
  end

  describe "GET new" do
    it "assigns a new moto_engine_size as @moto_engine_size" do
      MotoEngineSize.stub(:new) { mock_moto_engine_size }
      get :new
      assigns(:moto_engine_size).should be(mock_moto_engine_size)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_engine_size as @moto_engine_size" do
      MotoEngineSize.stub(:find).with("37") { mock_moto_engine_size }
      get :edit, :id => "37"
      assigns(:moto_engine_size).should be(mock_moto_engine_size)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_engine_size as @moto_engine_size" do
        MotoEngineSize.stub(:new).with({'these' => 'params'}) { mock_moto_engine_size(:save => true) }
        post :create, :moto_engine_size => {'these' => 'params'}
        assigns(:moto_engine_size).should be(mock_moto_engine_size)
      end

      it "redirects to the created moto_engine_size" do
        MotoEngineSize.stub(:new) { mock_moto_engine_size(:save => true) }
        post :create, :moto_engine_size => {}
        response.should redirect_to(moto_engine_size_url(mock_moto_engine_size))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_engine_size as @moto_engine_size" do
        MotoEngineSize.stub(:new).with({'these' => 'params'}) { mock_moto_engine_size(:save => false) }
        post :create, :moto_engine_size => {'these' => 'params'}
        assigns(:moto_engine_size).should be(mock_moto_engine_size)
      end

      it "re-renders the 'new' template" do
        MotoEngineSize.stub(:new) { mock_moto_engine_size(:save => false) }
        post :create, :moto_engine_size => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_engine_size" do
        MotoEngineSize.stub(:find).with("37") { mock_moto_engine_size }
        mock_moto_engine_size.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_engine_size => {'these' => 'params'}
      end

      it "assigns the requested moto_engine_size as @moto_engine_size" do
        MotoEngineSize.stub(:find) { mock_moto_engine_size(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_engine_size).should be(mock_moto_engine_size)
      end

      it "redirects to the moto_engine_size" do
        MotoEngineSize.stub(:find) { mock_moto_engine_size(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_engine_size_url(mock_moto_engine_size))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_engine_size as @moto_engine_size" do
        MotoEngineSize.stub(:find) { mock_moto_engine_size(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_engine_size).should be(mock_moto_engine_size)
      end

      it "re-renders the 'edit' template" do
        MotoEngineSize.stub(:find) { mock_moto_engine_size(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_engine_size" do
      MotoEngineSize.stub(:find).with("37") { mock_moto_engine_size }
      mock_moto_engine_size.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_engine_sizes list" do
      MotoEngineSize.stub(:find) { mock_moto_engine_size }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_engine_sizes_url)
    end
  end

end
