require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MotoUserPhonesController do

  def mock_moto_user_phone(stubs={})
    @mock_moto_user_phone ||= mock_model(MotoUserPhone, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moto_user_phones as @moto_user_phones" do
      MotoUserPhone.stub(:all) { [mock_moto_user_phone] }
      get :index
      assigns(:moto_user_phones).should eq([mock_moto_user_phone])
    end
  end

  describe "GET show" do
    it "assigns the requested moto_user_phone as @moto_user_phone" do
      MotoUserPhone.stub(:find).with("37") { mock_moto_user_phone }
      get :show, :id => "37"
      assigns(:moto_user_phone).should be(mock_moto_user_phone)
    end
  end

  describe "GET new" do
    it "assigns a new moto_user_phone as @moto_user_phone" do
      MotoUserPhone.stub(:new) { mock_moto_user_phone }
      get :new
      assigns(:moto_user_phone).should be(mock_moto_user_phone)
    end
  end

  describe "GET edit" do
    it "assigns the requested moto_user_phone as @moto_user_phone" do
      MotoUserPhone.stub(:find).with("37") { mock_moto_user_phone }
      get :edit, :id => "37"
      assigns(:moto_user_phone).should be(mock_moto_user_phone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moto_user_phone as @moto_user_phone" do
        MotoUserPhone.stub(:new).with({'these' => 'params'}) { mock_moto_user_phone(:save => true) }
        post :create, :moto_user_phone => {'these' => 'params'}
        assigns(:moto_user_phone).should be(mock_moto_user_phone)
      end

      it "redirects to the created moto_user_phone" do
        MotoUserPhone.stub(:new) { mock_moto_user_phone(:save => true) }
        post :create, :moto_user_phone => {}
        response.should redirect_to(moto_user_phone_url(mock_moto_user_phone))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moto_user_phone as @moto_user_phone" do
        MotoUserPhone.stub(:new).with({'these' => 'params'}) { mock_moto_user_phone(:save => false) }
        post :create, :moto_user_phone => {'these' => 'params'}
        assigns(:moto_user_phone).should be(mock_moto_user_phone)
      end

      it "re-renders the 'new' template" do
        MotoUserPhone.stub(:new) { mock_moto_user_phone(:save => false) }
        post :create, :moto_user_phone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moto_user_phone" do
        MotoUserPhone.stub(:find).with("37") { mock_moto_user_phone }
        mock_moto_user_phone.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moto_user_phone => {'these' => 'params'}
      end

      it "assigns the requested moto_user_phone as @moto_user_phone" do
        MotoUserPhone.stub(:find) { mock_moto_user_phone(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moto_user_phone).should be(mock_moto_user_phone)
      end

      it "redirects to the moto_user_phone" do
        MotoUserPhone.stub(:find) { mock_moto_user_phone(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moto_user_phone_url(mock_moto_user_phone))
      end
    end

    describe "with invalid params" do
      it "assigns the moto_user_phone as @moto_user_phone" do
        MotoUserPhone.stub(:find) { mock_moto_user_phone(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moto_user_phone).should be(mock_moto_user_phone)
      end

      it "re-renders the 'edit' template" do
        MotoUserPhone.stub(:find) { mock_moto_user_phone(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moto_user_phone" do
      MotoUserPhone.stub(:find).with("37") { mock_moto_user_phone }
      mock_moto_user_phone.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moto_user_phones list" do
      MotoUserPhone.stub(:find) { mock_moto_user_phone }
      delete :destroy, :id => "1"
      response.should redirect_to(moto_user_phones_url)
    end
  end

end
