require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StorageEquipmentsController do

  def mock_storage_equipment(stubs={})
    @mock_storage_equipment ||= mock_model(StorageEquipment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all storage_equipments as @storage_equipments" do
      StorageEquipment.stub(:all) { [mock_storage_equipment] }
      get :index
      assigns(:storage_equipments).should eq([mock_storage_equipment])
    end
  end

  describe "GET show" do
    it "assigns the requested storage_equipment as @storage_equipment" do
      StorageEquipment.stub(:find).with("37") { mock_storage_equipment }
      get :show, :id => "37"
      assigns(:storage_equipment).should be(mock_storage_equipment)
    end
  end

  describe "GET new" do
    it "assigns a new storage_equipment as @storage_equipment" do
      StorageEquipment.stub(:new) { mock_storage_equipment }
      get :new
      assigns(:storage_equipment).should be(mock_storage_equipment)
    end
  end

  describe "GET edit" do
    it "assigns the requested storage_equipment as @storage_equipment" do
      StorageEquipment.stub(:find).with("37") { mock_storage_equipment }
      get :edit, :id => "37"
      assigns(:storage_equipment).should be(mock_storage_equipment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created storage_equipment as @storage_equipment" do
        StorageEquipment.stub(:new).with({'these' => 'params'}) { mock_storage_equipment(:save => true) }
        post :create, :storage_equipment => {'these' => 'params'}
        assigns(:storage_equipment).should be(mock_storage_equipment)
      end

      it "redirects to the created storage_equipment" do
        StorageEquipment.stub(:new) { mock_storage_equipment(:save => true) }
        post :create, :storage_equipment => {}
        response.should redirect_to(storage_equipment_url(mock_storage_equipment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved storage_equipment as @storage_equipment" do
        StorageEquipment.stub(:new).with({'these' => 'params'}) { mock_storage_equipment(:save => false) }
        post :create, :storage_equipment => {'these' => 'params'}
        assigns(:storage_equipment).should be(mock_storage_equipment)
      end

      it "re-renders the 'new' template" do
        StorageEquipment.stub(:new) { mock_storage_equipment(:save => false) }
        post :create, :storage_equipment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested storage_equipment" do
        StorageEquipment.stub(:find).with("37") { mock_storage_equipment }
        mock_storage_equipment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :storage_equipment => {'these' => 'params'}
      end

      it "assigns the requested storage_equipment as @storage_equipment" do
        StorageEquipment.stub(:find) { mock_storage_equipment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:storage_equipment).should be(mock_storage_equipment)
      end

      it "redirects to the storage_equipment" do
        StorageEquipment.stub(:find) { mock_storage_equipment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(storage_equipment_url(mock_storage_equipment))
      end
    end

    describe "with invalid params" do
      it "assigns the storage_equipment as @storage_equipment" do
        StorageEquipment.stub(:find) { mock_storage_equipment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:storage_equipment).should be(mock_storage_equipment)
      end

      it "re-renders the 'edit' template" do
        StorageEquipment.stub(:find) { mock_storage_equipment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested storage_equipment" do
      StorageEquipment.stub(:find).with("37") { mock_storage_equipment }
      mock_storage_equipment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the storage_equipments list" do
      StorageEquipment.stub(:find) { mock_storage_equipment }
      delete :destroy, :id => "1"
      response.should redirect_to(storage_equipments_url)
    end
  end

end
