require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SubVehiclesController do

  def mock_sub_vehicle(stubs={})
    @mock_sub_vehicle ||= mock_model(SubVehicle, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sub_vehicles as @sub_vehicles" do
      SubVehicle.stub(:all) { [mock_sub_vehicle] }
      get :index
      assigns(:sub_vehicles).should eq([mock_sub_vehicle])
    end
  end

  describe "GET show" do
    it "assigns the requested sub_vehicle as @sub_vehicle" do
      SubVehicle.stub(:find).with("37") { mock_sub_vehicle }
      get :show, :id => "37"
      assigns(:sub_vehicle).should be(mock_sub_vehicle)
    end
  end

  describe "GET new" do
    it "assigns a new sub_vehicle as @sub_vehicle" do
      SubVehicle.stub(:new) { mock_sub_vehicle }
      get :new
      assigns(:sub_vehicle).should be(mock_sub_vehicle)
    end
  end

  describe "GET edit" do
    it "assigns the requested sub_vehicle as @sub_vehicle" do
      SubVehicle.stub(:find).with("37") { mock_sub_vehicle }
      get :edit, :id => "37"
      assigns(:sub_vehicle).should be(mock_sub_vehicle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sub_vehicle as @sub_vehicle" do
        SubVehicle.stub(:new).with({'these' => 'params'}) { mock_sub_vehicle(:save => true) }
        post :create, :sub_vehicle => {'these' => 'params'}
        assigns(:sub_vehicle).should be(mock_sub_vehicle)
      end

      it "redirects to the created sub_vehicle" do
        SubVehicle.stub(:new) { mock_sub_vehicle(:save => true) }
        post :create, :sub_vehicle => {}
        response.should redirect_to(sub_vehicle_url(mock_sub_vehicle))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sub_vehicle as @sub_vehicle" do
        SubVehicle.stub(:new).with({'these' => 'params'}) { mock_sub_vehicle(:save => false) }
        post :create, :sub_vehicle => {'these' => 'params'}
        assigns(:sub_vehicle).should be(mock_sub_vehicle)
      end

      it "re-renders the 'new' template" do
        SubVehicle.stub(:new) { mock_sub_vehicle(:save => false) }
        post :create, :sub_vehicle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sub_vehicle" do
        SubVehicle.stub(:find).with("37") { mock_sub_vehicle }
        mock_sub_vehicle.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sub_vehicle => {'these' => 'params'}
      end

      it "assigns the requested sub_vehicle as @sub_vehicle" do
        SubVehicle.stub(:find) { mock_sub_vehicle(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sub_vehicle).should be(mock_sub_vehicle)
      end

      it "redirects to the sub_vehicle" do
        SubVehicle.stub(:find) { mock_sub_vehicle(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sub_vehicle_url(mock_sub_vehicle))
      end
    end

    describe "with invalid params" do
      it "assigns the sub_vehicle as @sub_vehicle" do
        SubVehicle.stub(:find) { mock_sub_vehicle(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sub_vehicle).should be(mock_sub_vehicle)
      end

      it "re-renders the 'edit' template" do
        SubVehicle.stub(:find) { mock_sub_vehicle(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sub_vehicle" do
      SubVehicle.stub(:find).with("37") { mock_sub_vehicle }
      mock_sub_vehicle.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sub_vehicles list" do
      SubVehicle.stub(:find) { mock_sub_vehicle }
      delete :destroy, :id => "1"
      response.should redirect_to(sub_vehicles_url)
    end
  end

end
