require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SubCarsController do

  def mock_sub_car(stubs={})
    @mock_sub_car ||= mock_model(SubCar, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sub_cars as @sub_cars" do
      SubCar.stub(:all) { [mock_sub_car] }
      get :index
      assigns(:sub_cars).should eq([mock_sub_car])
    end
  end

  describe "GET show" do
    it "assigns the requested sub_car as @sub_car" do
      SubCar.stub(:find).with("37") { mock_sub_car }
      get :show, :id => "37"
      assigns(:sub_car).should be(mock_sub_car)
    end
  end

  describe "GET new" do
    it "assigns a new sub_car as @sub_car" do
      SubCar.stub(:new) { mock_sub_car }
      get :new
      assigns(:sub_car).should be(mock_sub_car)
    end
  end

  describe "GET edit" do
    it "assigns the requested sub_car as @sub_car" do
      SubCar.stub(:find).with("37") { mock_sub_car }
      get :edit, :id => "37"
      assigns(:sub_car).should be(mock_sub_car)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sub_car as @sub_car" do
        SubCar.stub(:new).with({'these' => 'params'}) { mock_sub_car(:save => true) }
        post :create, :sub_car => {'these' => 'params'}
        assigns(:sub_car).should be(mock_sub_car)
      end

      it "redirects to the created sub_car" do
        SubCar.stub(:new) { mock_sub_car(:save => true) }
        post :create, :sub_car => {}
        response.should redirect_to(sub_car_url(mock_sub_car))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sub_car as @sub_car" do
        SubCar.stub(:new).with({'these' => 'params'}) { mock_sub_car(:save => false) }
        post :create, :sub_car => {'these' => 'params'}
        assigns(:sub_car).should be(mock_sub_car)
      end

      it "re-renders the 'new' template" do
        SubCar.stub(:new) { mock_sub_car(:save => false) }
        post :create, :sub_car => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sub_car" do
        SubCar.stub(:find).with("37") { mock_sub_car }
        mock_sub_car.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sub_car => {'these' => 'params'}
      end

      it "assigns the requested sub_car as @sub_car" do
        SubCar.stub(:find) { mock_sub_car(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sub_car).should be(mock_sub_car)
      end

      it "redirects to the sub_car" do
        SubCar.stub(:find) { mock_sub_car(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sub_car_url(mock_sub_car))
      end
    end

    describe "with invalid params" do
      it "assigns the sub_car as @sub_car" do
        SubCar.stub(:find) { mock_sub_car(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sub_car).should be(mock_sub_car)
      end

      it "re-renders the 'edit' template" do
        SubCar.stub(:find) { mock_sub_car(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sub_car" do
      SubCar.stub(:find).with("37") { mock_sub_car }
      mock_sub_car.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sub_cars list" do
      SubCar.stub(:find) { mock_sub_car }
      delete :destroy, :id => "1"
      response.should redirect_to(sub_cars_url)
    end
  end

end
