require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TotalOwnersController do

  def mock_total_owner(stubs={})
    @mock_total_owner ||= mock_model(TotalOwner, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all total_owners as @total_owners" do
      TotalOwner.stub(:all) { [mock_total_owner] }
      get :index
      assigns(:total_owners).should eq([mock_total_owner])
    end
  end

  describe "GET show" do
    it "assigns the requested total_owner as @total_owner" do
      TotalOwner.stub(:find).with("37") { mock_total_owner }
      get :show, :id => "37"
      assigns(:total_owner).should be(mock_total_owner)
    end
  end

  describe "GET new" do
    it "assigns a new total_owner as @total_owner" do
      TotalOwner.stub(:new) { mock_total_owner }
      get :new
      assigns(:total_owner).should be(mock_total_owner)
    end
  end

  describe "GET edit" do
    it "assigns the requested total_owner as @total_owner" do
      TotalOwner.stub(:find).with("37") { mock_total_owner }
      get :edit, :id => "37"
      assigns(:total_owner).should be(mock_total_owner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created total_owner as @total_owner" do
        TotalOwner.stub(:new).with({'these' => 'params'}) { mock_total_owner(:save => true) }
        post :create, :total_owner => {'these' => 'params'}
        assigns(:total_owner).should be(mock_total_owner)
      end

      it "redirects to the created total_owner" do
        TotalOwner.stub(:new) { mock_total_owner(:save => true) }
        post :create, :total_owner => {}
        response.should redirect_to(total_owner_url(mock_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved total_owner as @total_owner" do
        TotalOwner.stub(:new).with({'these' => 'params'}) { mock_total_owner(:save => false) }
        post :create, :total_owner => {'these' => 'params'}
        assigns(:total_owner).should be(mock_total_owner)
      end

      it "re-renders the 'new' template" do
        TotalOwner.stub(:new) { mock_total_owner(:save => false) }
        post :create, :total_owner => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested total_owner" do
        TotalOwner.stub(:find).with("37") { mock_total_owner }
        mock_total_owner.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :total_owner => {'these' => 'params'}
      end

      it "assigns the requested total_owner as @total_owner" do
        TotalOwner.stub(:find) { mock_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:total_owner).should be(mock_total_owner)
      end

      it "redirects to the total_owner" do
        TotalOwner.stub(:find) { mock_total_owner(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(total_owner_url(mock_total_owner))
      end
    end

    describe "with invalid params" do
      it "assigns the total_owner as @total_owner" do
        TotalOwner.stub(:find) { mock_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:total_owner).should be(mock_total_owner)
      end

      it "re-renders the 'edit' template" do
        TotalOwner.stub(:find) { mock_total_owner(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested total_owner" do
      TotalOwner.stub(:find).with("37") { mock_total_owner }
      mock_total_owner.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the total_owners list" do
      TotalOwner.stub(:find) { mock_total_owner }
      delete :destroy, :id => "1"
      response.should redirect_to(total_owners_url)
    end
  end

end
